/* automatically generated by rust-bindgen 0.71.1 */

// Generated by bindgen — regenerate with `cargo xtask generate-bindings`.
//
// Source: cpp/astcenc.h
#![allow(
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    dead_code
)]

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct astcenc_context {
    _unused: [u8; 0],
}
pub const astcenc_error_ASTCENC_SUCCESS: astcenc_error = 0;
pub const astcenc_error_ASTCENC_ERR_OUT_OF_MEM: astcenc_error = 1;
pub const astcenc_error_ASTCENC_ERR_BAD_CPU_FLOAT: astcenc_error = 2;
pub const astcenc_error_ASTCENC_ERR_BAD_PARAM: astcenc_error = 3;
pub const astcenc_error_ASTCENC_ERR_BAD_BLOCK_SIZE: astcenc_error = 4;
pub const astcenc_error_ASTCENC_ERR_BAD_PROFILE: astcenc_error = 5;
pub const astcenc_error_ASTCENC_ERR_BAD_QUALITY: astcenc_error = 6;
pub const astcenc_error_ASTCENC_ERR_BAD_SWIZZLE: astcenc_error = 7;
pub const astcenc_error_ASTCENC_ERR_BAD_FLAGS: astcenc_error = 8;
pub const astcenc_error_ASTCENC_ERR_BAD_CONTEXT: astcenc_error = 9;
pub const astcenc_error_ASTCENC_ERR_NOT_IMPLEMENTED: astcenc_error = 10;
pub const astcenc_error_ASTCENC_ERR_BAD_DECODE_MODE: astcenc_error = 11;
pub type astcenc_error = ::std::os::raw::c_int;
pub const astcenc_profile_ASTCENC_PRF_LDR_SRGB: astcenc_profile = 0;
pub const astcenc_profile_ASTCENC_PRF_LDR: astcenc_profile = 1;
pub const astcenc_profile_ASTCENC_PRF_HDR_RGB_LDR_A: astcenc_profile = 2;
pub const astcenc_profile_ASTCENC_PRF_HDR: astcenc_profile = 3;
pub type astcenc_profile = ::std::os::raw::c_int;
pub const ASTCENC_PRE_FASTEST: f32 = 0.0;
pub const ASTCENC_PRE_FAST: f32 = 10.0;
pub const ASTCENC_PRE_MEDIUM: f32 = 60.0;
pub const ASTCENC_PRE_THOROUGH: f32 = 98.0;
pub const ASTCENC_PRE_VERYTHOROUGH: f32 = 99.0;
pub const ASTCENC_PRE_EXHAUSTIVE: f32 = 100.0;
pub const astcenc_swz_ASTCENC_SWZ_R: astcenc_swz = 0;
pub const astcenc_swz_ASTCENC_SWZ_G: astcenc_swz = 1;
pub const astcenc_swz_ASTCENC_SWZ_B: astcenc_swz = 2;
pub const astcenc_swz_ASTCENC_SWZ_A: astcenc_swz = 3;
pub const astcenc_swz_ASTCENC_SWZ_0: astcenc_swz = 4;
pub const astcenc_swz_ASTCENC_SWZ_1: astcenc_swz = 5;
pub const astcenc_swz_ASTCENC_SWZ_Z: astcenc_swz = 6;
pub type astcenc_swz = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct astcenc_swizzle {
    pub r: astcenc_swz,
    pub g: astcenc_swz,
    pub b: astcenc_swz,
    pub a: astcenc_swz,
}
pub const astcenc_type_ASTCENC_TYPE_U8: astcenc_type = 0;
pub const astcenc_type_ASTCENC_TYPE_F16: astcenc_type = 1;
pub const astcenc_type_ASTCENC_TYPE_F32: astcenc_type = 2;
pub type astcenc_type = ::std::os::raw::c_int;
pub type astcenc_progress_callback = ::std::option::Option<unsafe extern "C" fn(arg1: f32)>;
pub const ASTCENC_FLG_MAP_NORMAL: ::std::os::raw::c_uint = 1;
pub const ASTCENC_FLG_USE_DECODE_UNORM8: ::std::os::raw::c_uint = 2;
pub const ASTCENC_FLG_USE_ALPHA_WEIGHT: ::std::os::raw::c_uint = 4;
pub const ASTCENC_FLG_USE_PERCEPTUAL: ::std::os::raw::c_uint = 8;
pub const ASTCENC_FLG_DECOMPRESS_ONLY: ::std::os::raw::c_uint = 16;
pub const ASTCENC_FLG_SELF_DECOMPRESS_ONLY: ::std::os::raw::c_uint = 32;
pub const ASTCENC_FLG_MAP_RGBM: ::std::os::raw::c_uint = 64;
pub const ASTCENC_ALL_FLAGS: ::std::os::raw::c_uint = 127;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct astcenc_config {
    pub profile: astcenc_profile,
    pub flags: ::std::os::raw::c_uint,
    pub block_x: ::std::os::raw::c_uint,
    pub block_y: ::std::os::raw::c_uint,
    pub block_z: ::std::os::raw::c_uint,
    pub cw_r_weight: f32,
    pub cw_g_weight: f32,
    pub cw_b_weight: f32,
    pub cw_a_weight: f32,
    pub a_scale_radius: ::std::os::raw::c_uint,
    pub rgbm_m_scale: f32,
    pub tune_partition_count_limit: ::std::os::raw::c_uint,
    pub tune_2partition_index_limit: ::std::os::raw::c_uint,
    pub tune_3partition_index_limit: ::std::os::raw::c_uint,
    pub tune_4partition_index_limit: ::std::os::raw::c_uint,
    pub tune_block_mode_limit: ::std::os::raw::c_uint,
    pub tune_refinement_limit: ::std::os::raw::c_uint,
    pub tune_candidate_limit: ::std::os::raw::c_uint,
    pub tune_2partitioning_candidate_limit: ::std::os::raw::c_uint,
    pub tune_3partitioning_candidate_limit: ::std::os::raw::c_uint,
    pub tune_4partitioning_candidate_limit: ::std::os::raw::c_uint,
    pub tune_db_limit: f32,
    pub tune_mse_overshoot: f32,
    pub tune_2partition_early_out_limit_factor: f32,
    pub tune_3partition_early_out_limit_factor: f32,
    pub tune_2plane_early_out_limit_correlation: f32,
    pub tune_search_mode0_enable: f32,
    pub progress_callback: astcenc_progress_callback,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct astcenc_image {
    pub dim_x: ::std::os::raw::c_uint,
    pub dim_y: ::std::os::raw::c_uint,
    pub dim_z: ::std::os::raw::c_uint,
    pub data_type: astcenc_type,
    pub data: *mut *mut ::std::os::raw::c_void,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct astcenc_block_info {
    pub profile: astcenc_profile,
    pub block_x: ::std::os::raw::c_uint,
    pub block_y: ::std::os::raw::c_uint,
    pub block_z: ::std::os::raw::c_uint,
    pub texel_count: ::std::os::raw::c_uint,
    pub is_error_block: bool,
    pub is_constant_block: bool,
    pub is_hdr_block: bool,
    pub is_dual_plane_block: bool,
    pub partition_count: ::std::os::raw::c_uint,
    pub partition_index: ::std::os::raw::c_uint,
    pub dual_plane_component: ::std::os::raw::c_uint,
    pub color_endpoint_modes: [::std::os::raw::c_uint; 4usize],
    pub color_level_count: ::std::os::raw::c_uint,
    pub weight_level_count: ::std::os::raw::c_uint,
    pub weight_x: ::std::os::raw::c_uint,
    pub weight_y: ::std::os::raw::c_uint,
    pub weight_z: ::std::os::raw::c_uint,
    pub color_endpoints: [[[f32; 4usize]; 2usize]; 4usize],
    pub weight_values_plane1: [f32; 216usize],
    pub weight_values_plane2: [f32; 216usize],
    pub partition_assignment: [u8; 216usize],
}
