[workspace]
members = [
  "crates/*",
  "crates/ctt-intel-texture-compressor/prebuilt",
  "crates/ctt-bc7enc-rdo/prebuilt",
  "xtask",
]
resolver = "3"

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.85"
authors = ["The ctt developers"]
license = "MIT OR Apache-2.0 OR Zlib"
repository = "https://github.com/cwfitzgerald/ctt"

[workspace.lints]

[workspace.dependencies]
ctt = { path = "crates/ctt", version = "0.2", default-features = false }
ctt-intel-texture-compressor = { path = "crates/ctt-intel-texture-compressor", version = "0.2", default-features = false }
ctt-intel-texture-compressor-prebuilt = { path = "crates/ctt-intel-texture-compressor/prebuilt", version = "0.2", default-features = false }
ctt-bc7enc-rdo = { path = "crates/ctt-bc7enc-rdo", version = "0.2", default-features = false }
ctt-bc7enc-rdo-prebuilt = { path = "crates/ctt-bc7enc-rdo/prebuilt", version = "0.2", default-features = false }
ispc-build-utils = { path = "crates/ispc-build-utils", version = "0.2", default-features = false }

anyhow = "1"
bytemuck = "1"
clap = { version = "4", features = ["derive"] }
ddsfile = "0.5"
fern = "0.7"
half = "2"
image = "0.25"
ktx2 = "0.4"
log = "0.4"
thiserror = "2"
