[package]
name = "ctt-bc7enc-rdo-prebuilt"
version.workspace = true
edition.workspace = true
authors = [
    "The ctt developers",
    "Rich Geldreich <richgel99@gmail.com>",
]
license = "(MIT OR Apache-2.0) AND Apache-2.0"
repository.workspace = true
rust-version.workspace = true
description = "Prebuilt ISPC static libraries for ctt-bc7enc-rdo"
keywords = ["texture", "compression", "bc7", "gpu"]
categories = ["graphics", "compression"]
build = "build.rs"
links = "bc7e"
include = [
    "src/**",
    "build.rs",
    "bins/**",
    "Cargo.toml",
]

[build-dependencies]
ispc-build-utils = { workspace = true }

[lints]
workspace = true
