/*
 * ctt — C bindings for the ctt texture compression library.
 *
 * This header is generated by cbindgen via `cargo xtask generate-c-header`.
 * Do not edit by hand.
 *
 *
 * Overview
 * --------
 *
 * ctt converts and (de)compresses GPU textures. Two top-level workflows are
 * exposed:
 *
 *   - Encode / convert: build a `ctt_image` from one or more `ctt_surface`s,
 *     fill in a `ctt_convert_settings`, and call `ctt_convert`. The result
 *     is a `ctt_pipeline_output` carrying either container bytes (KTX2 / DDS)
 *     or, when `Container::Raw` is requested, a freshly-decoded image.
 *
 *   - Decode: call `ctt_decode_container` (auto-detect from magic bytes) or
 *     `ctt_decode_container_as` (caller specifies KTX2 vs DDS) on a buffer
 *     of file bytes; the returned `ctt_image` exposes per-`(layer, mip)`
 *     surface metadata and data via the `ctt_image_surface_*` accessors.
 *
 * A typical encode pipeline:
 *
 *     ctt_surface *s = ctt_surface_create(pixels, len, w, h, 1, w*4, 0,
 *                          CTT_FORMAT_R8G8B8A8_UNORM,
 *                          CTT_COLOR_SPACE_SRGB,
 *                          CTT_ALPHA_MODE_STRAIGHT);
 *     ctt_image *img = ctt_image_create(CTT_TEXTURE_KIND_TEXTURE2D);
 *     size_t layer; ctt_image_add_layer(img, &layer);
 *     ctt_image_push_mip(img, layer, s);          // consumes `s`
 *
 *     ctt_convert_settings cfg = ctt_convert_settings_default();
 *     cfg.format = (ctt_target_format){
 *         .tag = CTT_TARGET_FORMAT_COMPRESSED,
 *         .compressed = { CTT_FORMAT_BC7_UNORM_BLOCK, ctt_encoder_auto() },
 *     };
 *     cfg.mipmap = true;
 *
 *     ctt_pipeline_output *out = NULL;
 *     ctt_status st = ctt_convert(img, &cfg, &out);   // consumes `img`
 *     // st == CTT_STATUS_OK: `out` carries KTX2 bytes (the default container).
 *     ctt_pipeline_output_destroy(out);
 *
 *
 * Memory model
 * ------------
 *
 * All heap allocation happens on the Rust side, so callers must not free
 * pointers returned by ctt with their own allocator. Each opaque type
 * (`ctt_surface`, `ctt_image`, `ctt_cubemap_input`, `ctt_pipeline_output`)
 * has a matching `*_destroy` function; passing `NULL` is always safe.
 *
 * APIs that consume an input (e.g. `ctt_convert`, `ctt_split_cubemap`,
 * `ctt_image_push_mip`, `ctt_cubemap_input_*`) take ownership of the passed-in
 * handle on both success and failure: the caller must not call `*_destroy`
 * on a consumed handle. Each consuming function's doc comment calls this out.
 *
 * Borrowed pointers returned by accessors (`ctt_surface_data`,
 * `ctt_image_surface_data`, `ctt_pipeline_output_encoded_data`) are valid
 * only as long as the owning handle is alive and unmutated. Copy out before
 * destroying the owner.
 *
 *
 * Errors
 * ------
 *
 * Functions that can fail return a `ctt_status`. `CTT_STATUS_OK` (`0`) means
 * success; negative codes are errors. A human-readable explanation of the
 * most recent failure on the calling thread is available via
 * `ctt_last_error_message`, valid until the next ctt call on that thread.
 * Functions that return a pointer (e.g. `ctt_surface_create`) signal failure
 * by returning `NULL` and also set the error message.
 *
 * Getter functions (`ctt_image_surface_*`, `ctt_surface_*`) do not set an
 * error message; out-of-range indices or null handles return a documented
 * sentinel (`NULL` for pointers, `0` or the lowest enum value otherwise).
 *
 *
 * Threading
 * ---------
 *
 * Handles are not internally synchronized — do not share a single handle
 * across threads without external synchronization. Distinct handles may be
 * used from different threads concurrently. The error-message slot is
 * thread-local.
 *
 *
 * Formats
 * -------
 *
 * Format values follow Vulkan's VkFormat enumeration; a non-exhaustive list
 * of common values is provided as `CTT_FORMAT_*` constants. Arbitrary
 * VkFormat values are accepted and may be useful for round-tripping
 * container files that carry an exotic format. `0` (`VK_FORMAT_UNDEFINED`)
 * is never a valid input.
 */


#ifndef CTT_H
#define CTT_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

/**
 * Universal quality preset all encoders understand.
 */
enum ctt_quality
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    CTT_QUALITY_ULTRA_FAST = 0,
    CTT_QUALITY_VERY_FAST = 1,
    CTT_QUALITY_FAST = 2,
    CTT_QUALITY_BASIC = 3,
    CTT_QUALITY_SLOW = 4,
    CTT_QUALITY_VERY_SLOW = 5,
};
#ifndef __cplusplus
typedef uint8_t ctt_quality;
#endif // __cplusplus

/**
 * Color space metadata for a surface.
 */
enum ctt_color_space
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    CTT_COLOR_SPACE_SRGB = 0,
    CTT_COLOR_SPACE_LINEAR = 1,
};
#ifndef __cplusplus
typedef uint8_t ctt_color_space;
#endif // __cplusplus

/**
 * Alpha interpretation for a surface.
 */
enum ctt_alpha_mode
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    CTT_ALPHA_MODE_STRAIGHT = 0,
    CTT_ALPHA_MODE_PREMULTIPLIED = 1,
    CTT_ALPHA_MODE_OPAQUE = 2,
};
#ifndef __cplusplus
typedef uint8_t ctt_alpha_mode;
#endif // __cplusplus

/**
 * One channel of a [`Swizzle`].
 */
enum ctt_swizzle_channel
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    CTT_SWIZZLE_CHANNEL_R = 0,
    CTT_SWIZZLE_CHANNEL_G = 1,
    CTT_SWIZZLE_CHANNEL_B = 2,
    CTT_SWIZZLE_CHANNEL_A = 3,
    CTT_SWIZZLE_CHANNEL_ZERO = 4,
    CTT_SWIZZLE_CHANNEL_ONE = 5,
};
#ifndef __cplusplus
typedef uint8_t ctt_swizzle_channel;
#endif // __cplusplus

/**
 * Filter used when downsampling for mipmap generation.
 */
enum ctt_mipmap_filter
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    CTT_MIPMAP_FILTER_NEAREST = 0,
    CTT_MIPMAP_FILTER_TRIANGLE = 1,
    CTT_MIPMAP_FILTER_CATMULL_ROM = 2,
    CTT_MIPMAP_FILTER_GAUSSIAN = 3,
    CTT_MIPMAP_FILTER_LANCZOS3 = 4,
};
#ifndef __cplusplus
typedef uint8_t ctt_mipmap_filter;
#endif // __cplusplus

/**
 * Status codes returned by ctt entry points.
 *
 * `CTT_STATUS_OK` (0) means success. Negative codes are errors. The most
 * recent error message is available via [`ctt_last_error_message`] until
 * the next ctt call on this thread.
 */
enum ctt_status
#ifdef __cplusplus
  : int32_t
#endif // __cplusplus
 {
    CTT_STATUS_OK = 0,
    CTT_STATUS_INVALID_DIMENSIONS = -1,
    CTT_STATUS_UNSUPPORTED_FORMAT = -2,
    CTT_STATUS_INVALID_SWIZZLE = -3,
    CTT_STATUS_CUBEMAP_FACE_COUNT = -4,
    CTT_STATUS_CUBEMAP_NON_UNIFORM_FACES = -5,
    CTT_STATUS_COMPRESSION = -6,
    CTT_STATUS_OUTPUT_ENCODING = -7,
    CTT_STATUS_INPUT_DECODING = -8,
    CTT_STATUS_DATA_LENGTH_MISMATCH = -9,
    CTT_STATUS_UNSUPPORTED_CONVERSION = -10,
    CTT_STATUS_LOSSY_CONVERSION = -11,
    CTT_STATUS_INVALID_IMAGE = -12,
    CTT_STATUS_NULL_POINTER = -100,
    CTT_STATUS_ENCODER_NOT_COMPILED_IN = -101,
    CTT_STATUS_INVALID_ARGUMENT = -102,
    CTT_STATUS_INTERNAL = -200,
};
#ifndef __cplusplus
typedef int32_t ctt_status;
#endif // __cplusplus

/**
 * Texture topology.
 *
 * Array-ness is implicit in the layer count: `Texture2D` uses one layer per
 * surface entry, `Cubemap` requires a multiple of 6 layers, `Texture3D`
 * requires exactly one layer (depth is carried on the surface).
 */
enum ctt_texture_kind
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    CTT_TEXTURE_KIND_TEXTURE2D = 0,
    CTT_TEXTURE_KIND_CUBEMAP = 1,
    CTT_TEXTURE_KIND_TEXTURE3D = 2,
};
#ifndef __cplusplus
typedef uint8_t ctt_texture_kind;
#endif // __cplusplus

/**
 * Detected container format.
 */
enum ctt_input_format
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    CTT_INPUT_FORMAT_KTX2 = 0,
    CTT_INPUT_FORMAT_DDS = 1,
};
#ifndef __cplusplus
typedef uint8_t ctt_input_format;
#endif // __cplusplus

/**
 * Tag for [`PipelineOutput`].
 */
enum ctt_pipeline_output_kind
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    CTT_PIPELINE_OUTPUT_KIND_ENCODED = 0,
    CTT_PIPELINE_OUTPUT_KIND_RAW = 1,
};
#ifndef __cplusplus
typedef uint8_t ctt_pipeline_output_kind;
#endif // __cplusplus

/**
 * Opaque handle to a cubemap input — either six separate face surfaces, a
 * cross-layout image, or a horizontal strip of six faces.
 *
 * Pass to [`ctt_split_cubemap`] to extract the six face surfaces.
 */
typedef struct ctt_cubemap_input ctt_cubemap_input;

/**
 * Opaque handle to a multi-layer / multi-mip image.
 *
 * `surfaces[i][j]` is layer `i`, mip level `j`. The meaning of the layer
 * axis depends on [`TextureKind`]: one entry per array layer for `Texture2D`,
 * six entries per cube for `Cubemap`, exactly one entry for `Texture3D`
 * (which carries depth on each surface).
 */
typedef struct ctt_image ctt_image;

/**
 * Opaque handle to a conversion result.
 *
 * The output is one of two variants, distinguished by
 * [`ctt_pipeline_output_get_kind`]:
 *
 * - `CTT_PIPELINE_OUTPUT_KIND_ENCODED` (any `Container` other than `Raw`):
 *   the result is a serialized container file (DDS or KTX2). Read the bytes
 *   with [`ctt_pipeline_output_encoded_data`] / [`ctt_pipeline_output_encoded_len`]
 *   and copy them out (e.g. write to disk) before destroying the output —
 *   the pointer is borrowed and becomes invalid once the output is freed.
 *
 * - `CTT_PIPELINE_OUTPUT_KIND_RAW` (only when `Container::Raw` was requested):
 *   the result is a processed `ctt_image_t`. Call
 *   [`ctt_pipeline_output_take_image`] to transfer ownership to the caller;
 *   from then on, walk the image with `ctt_image_layer_count` /
 *   `ctt_image_mip_count` and the `ctt_image_surface_*` accessors. The taken
 *   image must be freed with `ctt_image_destroy`.
 *
 * Always destroy the output with [`ctt_pipeline_output_destroy`] when done,
 * even after taking the image out of a `Raw` output.
 */
typedef struct ctt_pipeline_output ctt_pipeline_output;

/**
 * Opaque handle to a single image surface (raw pixels or compressed blocks).
 *
 * 2D surfaces use `depth == 1`; 3D (volume) surfaces use `depth > 1` with
 * all Z slices packed contiguously. Allocation is owned by ctt — call
 * [`ctt_surface_destroy`] when finished, unless the surface has been
 * consumed by another API.
 */
typedef struct ctt_surface ctt_surface;

/**
 * Settings for the `bc7enc-rdo` encoder.
 */
typedef struct {
    /**
     * Use perceptual error metrics (default `true`).
     */
    bool perceptual;
} ctt_bc7enc_settings;

/**
 * Settings for the Intel ISPC texture compressor.
 */
typedef struct {
    /**
     * Encode the alpha channel for BC7. No effect on other formats.
     */
    bool alpha;
} ctt_intel_settings;

/**
 * Settings for the etcpak encoder.
 */
typedef struct {
    /**
     * Enable dithering for ETC1 / BC1.
     */
    bool dither;
    /**
     * Enable heuristic-based fast mode selection for ETC2 RGB / RGBA.
     */
    bool use_heuristics;
} ctt_etcpak_settings;

/**
 * Settings for the AMD Compressonator encoder. Currently no fields are
 * exposed; this struct exists for ABI uniformity with the other encoders.
 */
typedef struct {
    uint8_t _reserved;
} ctt_amd_settings;

/**
 * Settings for the `astcenc` encoder. Currently no fields are exposed.
 */
typedef struct {
    uint8_t _reserved;
} ctt_astcenc_settings;

/**
 * User-facing encoder choice for compressed targets.
 *
 * `Auto` picks the best compiled-in encoder for the requested format. Other
 * variants pin a specific backend and carry its settings. All variants are
 * always present in the ABI; selecting an encoder whose feature is disabled
 * at compile time returns `CTT_STATUS_ENCODER_NOT_COMPILED_IN`.
 */
enum ctt_encoder_Tag
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    CTT_ENCODER_AUTO,
    CTT_ENCODER_BC7ENC,
    CTT_ENCODER_INTEL,
    CTT_ENCODER_ETCPAK,
    CTT_ENCODER_AMD,
    CTT_ENCODER_ASTCENC,
};
#ifndef __cplusplus
typedef uint8_t ctt_encoder_Tag;
#endif // __cplusplus

typedef struct {
    ctt_encoder_Tag tag;
    union {
        struct {
            ctt_bc7enc_settings bc7enc;
        };
        struct {
            ctt_intel_settings intel;
        };
        struct {
            ctt_etcpak_settings etcpak;
        };
        struct {
            ctt_amd_settings amd;
        };
        struct {
            ctt_astcenc_settings astcenc;
        };
    };
} ctt_encoder;

/**
 * A texel format. Values are Vulkan VkFormat values.
 *
 * Common values are exported as `CTT_FORMAT_*` constants; arbitrary VkFormat
 * values are also accepted (useful when round-tripping container files that
 * carry a format ctt does not specifically know about).
 */
typedef uint32_t ctt_format;

/**
 * Inner payload of the [`TargetFormat::Compressed`] variant.
 */
typedef struct {
    ctt_format format;
    ctt_encoder encoder;
} ctt_compressed_target_format;

/**
 * The target format for a conversion.
 *
 * `None` keeps the input format (no conversion). `Uncompressed` produces a
 * plain pixel format. `Compressed` block-encodes with the chosen
 * [`Encoder`].
 */
enum ctt_target_format_Tag
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    CTT_TARGET_FORMAT_NONE,
    CTT_TARGET_FORMAT_UNCOMPRESSED,
    CTT_TARGET_FORMAT_COMPRESSED,
};
#ifndef __cplusplus
typedef uint8_t ctt_target_format_Tag;
#endif // __cplusplus

typedef struct {
    ctt_target_format_Tag tag;
    union {
        struct {
            ctt_format uncompressed;
        };
        struct {
            ctt_compressed_target_format compressed;
        };
    };
} ctt_target_format;

/**
 * Output container format.
 *
 * `Ktx2` writes a plain KTX2 file. `Ktx2Zstd` / `Ktx2Zlib` apply the
 * corresponding KTX2 supercompression scheme; the carried integer is the
 * compression level passed to the underlying codec. `Raw` returns the
 * processed image without serializing into a file format.
 */
enum ctt_container_Tag
#ifdef __cplusplus
  : uint8_t
#endif // __cplusplus
 {
    CTT_CONTAINER_DDS,
    CTT_CONTAINER_KTX2,
    CTT_CONTAINER_KTX2_ZSTD,
    CTT_CONTAINER_KTX2_ZLIB,
    CTT_CONTAINER_RAW,
};
#ifndef __cplusplus
typedef uint8_t ctt_container_Tag;
#endif // __cplusplus

typedef struct {
    ctt_container_Tag tag;
    union {
        struct {
            int32_t ktx2_zstd;
        };
        struct {
            uint8_t ktx2_zlib;
        };
    };
} ctt_container;

/**
 * Optional [`ColorSpace`] (matches Rust's `Option<ColorSpace>`).
 */
typedef struct {
    bool present;
    ctt_color_space value;
} ctt_optional_color_space;

/**
 * Optional [`AlphaMode`] (matches Rust's `Option<AlphaMode>`).
 */
typedef struct {
    bool present;
    ctt_alpha_mode value;
} ctt_optional_alpha_mode;

/**
 * A 4-component swizzle pattern, ordered as the destination channels R,G,B,A.
 */
typedef struct {
    ctt_swizzle_channel channels[4];
} ctt_swizzle;

/**
 * Optional [`Swizzle`] (matches Rust's `Option<Swizzle>`).
 */
typedef struct {
    bool present;
    ctt_swizzle value;
} ctt_optional_swizzle;

/**
 * Optional `size_t` value (matches Rust's `Option<usize>`).
 */
typedef struct {
    bool present;
    size_t value;
} ctt_optional_size;

/**
 * Settings controlling a [`ctt_convert`] call.
 *
 * Build via [`ctt_convert_settings_default`] and overwrite fields, or
 * fill the struct directly. Optional fields have a `present` flag — set
 * it to `false` to keep the default behavior.
 */
typedef struct {
    ctt_target_format format;
    ctt_container container;
    ctt_quality quality;
    ctt_optional_color_space output_color_space;
    ctt_optional_alpha_mode output_alpha;
    ctt_optional_swizzle swizzle;
    bool mipmap;
    ctt_optional_size mipmap_count;
    ctt_mipmap_filter mipmap_filter;
} ctt_convert_settings;

/**
 * Optional metadata overrides applied to every surface in a decoded image.
 *
 * Each field's `present` flag selects whether to override the value the
 * container would otherwise provide.
 */
typedef struct {
    ctt_optional_color_space color_space;
    ctt_optional_alpha_mode alpha;
} ctt_input_overrides;

#define CTT_FORMAT_R8_UNORM 9

#define CTT_FORMAT_R8_SNORM 10

#define CTT_FORMAT_R8_UINT 13

#define CTT_FORMAT_R8_SINT 14

#define CTT_FORMAT_R8_SRGB 15

#define CTT_FORMAT_R8G8_UNORM 16

#define CTT_FORMAT_R8G8_SNORM 17

#define CTT_FORMAT_R8G8_UINT 20

#define CTT_FORMAT_R8G8_SINT 21

#define CTT_FORMAT_R8G8_SRGB 22

#define CTT_FORMAT_R8G8B8A8_UNORM 37

#define CTT_FORMAT_R8G8B8A8_SNORM 38

#define CTT_FORMAT_R8G8B8A8_UINT 41

#define CTT_FORMAT_R8G8B8A8_SINT 42

#define CTT_FORMAT_R8G8B8A8_SRGB 43

#define CTT_FORMAT_B8G8R8A8_UNORM 44

#define CTT_FORMAT_B8G8R8A8_SNORM 45

#define CTT_FORMAT_B8G8R8A8_UINT 48

#define CTT_FORMAT_B8G8R8A8_SINT 49

#define CTT_FORMAT_B8G8R8A8_SRGB 50

#define CTT_FORMAT_A2B10G10R10_UNORM_PACK32 64

#define CTT_FORMAT_A2B10G10R10_UINT_PACK32 68

#define CTT_FORMAT_B10G11R11_UFLOAT_PACK32 122

#define CTT_FORMAT_R16_UNORM 70

#define CTT_FORMAT_R16_SNORM 71

#define CTT_FORMAT_R16_UINT 74

#define CTT_FORMAT_R16_SINT 75

#define CTT_FORMAT_R16_SFLOAT 76

#define CTT_FORMAT_R16G16_UNORM 77

#define CTT_FORMAT_R16G16_SNORM 78

#define CTT_FORMAT_R16G16_UINT 81

#define CTT_FORMAT_R16G16_SINT 82

#define CTT_FORMAT_R16G16_SFLOAT 83

#define CTT_FORMAT_R16G16B16A16_UNORM 91

#define CTT_FORMAT_R16G16B16A16_SNORM 92

#define CTT_FORMAT_R16G16B16A16_UINT 95

#define CTT_FORMAT_R16G16B16A16_SINT 96

#define CTT_FORMAT_R16G16B16A16_SFLOAT 97

#define CTT_FORMAT_R32_UINT 98

#define CTT_FORMAT_R32_SINT 99

#define CTT_FORMAT_R32_SFLOAT 100

#define CTT_FORMAT_R32G32_UINT 101

#define CTT_FORMAT_R32G32_SINT 102

#define CTT_FORMAT_R32G32_SFLOAT 103

#define CTT_FORMAT_R32G32B32A32_UINT 107

#define CTT_FORMAT_R32G32B32A32_SINT 108

#define CTT_FORMAT_R32G32B32A32_SFLOAT 109

#define CTT_FORMAT_BC1_RGB_UNORM_BLOCK 131

#define CTT_FORMAT_BC1_RGB_SRGB_BLOCK 132

#define CTT_FORMAT_BC1_RGBA_UNORM_BLOCK 133

#define CTT_FORMAT_BC1_RGBA_SRGB_BLOCK 134

#define CTT_FORMAT_BC2_UNORM_BLOCK 135

#define CTT_FORMAT_BC2_SRGB_BLOCK 136

#define CTT_FORMAT_BC3_UNORM_BLOCK 137

#define CTT_FORMAT_BC3_SRGB_BLOCK 138

#define CTT_FORMAT_BC4_UNORM_BLOCK 139

#define CTT_FORMAT_BC4_SNORM_BLOCK 140

#define CTT_FORMAT_BC5_UNORM_BLOCK 141

#define CTT_FORMAT_BC5_SNORM_BLOCK 142

#define CTT_FORMAT_BC6H_UFLOAT_BLOCK 143

#define CTT_FORMAT_BC6H_SFLOAT_BLOCK 144

#define CTT_FORMAT_BC7_UNORM_BLOCK 145

#define CTT_FORMAT_BC7_SRGB_BLOCK 146

#define CTT_FORMAT_ETC2_R8G8B8_UNORM_BLOCK 147

#define CTT_FORMAT_ETC2_R8G8B8_SRGB_BLOCK 148

#define CTT_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK 149

#define CTT_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK 150

#define CTT_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK 151

#define CTT_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK 152

#define CTT_FORMAT_EAC_R11_UNORM_BLOCK 153

#define CTT_FORMAT_EAC_R11_SNORM_BLOCK 154

#define CTT_FORMAT_EAC_R11G11_UNORM_BLOCK 155

#define CTT_FORMAT_EAC_R11G11_SNORM_BLOCK 156

#define CTT_FORMAT_ASTC_4X4_UNORM_BLOCK 157

#define CTT_FORMAT_ASTC_4X4_SRGB_BLOCK 158

#define CTT_FORMAT_ASTC_5X4_UNORM_BLOCK 159

#define CTT_FORMAT_ASTC_5X4_SRGB_BLOCK 160

#define CTT_FORMAT_ASTC_5X5_UNORM_BLOCK 161

#define CTT_FORMAT_ASTC_5X5_SRGB_BLOCK 162

#define CTT_FORMAT_ASTC_6X5_UNORM_BLOCK 163

#define CTT_FORMAT_ASTC_6X5_SRGB_BLOCK 164

#define CTT_FORMAT_ASTC_6X6_UNORM_BLOCK 165

#define CTT_FORMAT_ASTC_6X6_SRGB_BLOCK 166

#define CTT_FORMAT_ASTC_8X5_UNORM_BLOCK 167

#define CTT_FORMAT_ASTC_8X5_SRGB_BLOCK 168

#define CTT_FORMAT_ASTC_8X6_UNORM_BLOCK 169

#define CTT_FORMAT_ASTC_8X6_SRGB_BLOCK 170

#define CTT_FORMAT_ASTC_8X8_UNORM_BLOCK 171

#define CTT_FORMAT_ASTC_8X8_SRGB_BLOCK 172

#define CTT_FORMAT_ASTC_10X5_UNORM_BLOCK 173

#define CTT_FORMAT_ASTC_10X5_SRGB_BLOCK 174

#define CTT_FORMAT_ASTC_10X6_UNORM_BLOCK 175

#define CTT_FORMAT_ASTC_10X6_SRGB_BLOCK 176

#define CTT_FORMAT_ASTC_10X8_UNORM_BLOCK 177

#define CTT_FORMAT_ASTC_10X8_SRGB_BLOCK 178

#define CTT_FORMAT_ASTC_10X10_UNORM_BLOCK 179

#define CTT_FORMAT_ASTC_10X10_SRGB_BLOCK 180

#define CTT_FORMAT_ASTC_12X10_UNORM_BLOCK 181

#define CTT_FORMAT_ASTC_12X10_SRGB_BLOCK 182

#define CTT_FORMAT_ASTC_12X12_UNORM_BLOCK 183

#define CTT_FORMAT_ASTC_12X12_SRGB_BLOCK 184

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Default settings for the `bc7enc-rdo` encoder.
 */
 ctt_bc7enc_settings ctt_bc7enc_settings_default(void);

 ctt_intel_settings ctt_intel_settings_default(void);

 ctt_etcpak_settings ctt_etcpak_settings_default(void);

 ctt_amd_settings ctt_amd_settings_default(void);

 ctt_astcenc_settings ctt_astcenc_settings_default(void);

 ctt_encoder ctt_encoder_auto(void);

/**
 * Default-constructed settings: input format preserved, KTX2 container,
 * `Basic` quality, no swizzle / mipmaps / overrides.
 */
 ctt_convert_settings ctt_convert_settings_default(void);

/**
 * Run the conversion pipeline.
 *
 * **Consumes** `image` on both success and failure — the handle must not be
 * destroyed by the caller after this call. On success, writes a freshly
 * allocated `ctt_pipeline_output_t` handle into `*out` (caller frees with
 * `ctt_pipeline_output_destroy`).
 */

ctt_status ctt_convert(ctt_image *image,
                       const ctt_convert_settings *settings,
                       ctt_pipeline_output **out);

/**
 * Build a cubemap input from six separate face surfaces, ordered
 * `+X, -X, +Y, -Y, +Z, -Z`.
 *
 * `faces` must point to an array of exactly six surface handles; **all
 * six are consumed** on both success and failure.
 */
 ctt_cubemap_input *ctt_cubemap_input_separate_faces(ctt_surface **faces);

/**
 * Build a cubemap input from a 4×3 cross-layout image. Consumes the surface.
 */
 ctt_cubemap_input *ctt_cubemap_input_cross(ctt_surface *surface);

/**
 * Build a cubemap input from a horizontal strip of 6 faces. Consumes the
 * surface.
 */
 ctt_cubemap_input *ctt_cubemap_input_strip(ctt_surface *surface);

/**
 * Destroy a cubemap input. `input` may be NULL.
 */
 void ctt_cubemap_input_destroy(ctt_cubemap_input *input);

/**
 * Split a cubemap input into six face surfaces.
 *
 * **Consumes** `input` on both success and failure. On success writes six
 * new surface handles into `out_faces[0..6]`, in `+X, -X, +Y, -Y, +Z, -Z`
 * order. On failure leaves `out_faces` untouched.
 *
 * `out_faces` must point to space for six `ctt_surface_t` pointers.
 */
 ctt_status ctt_split_cubemap(ctt_cubemap_input *input, ctt_surface **out_faces);

/**
 * Pointer to a NUL-terminated UTF-8 string describing the most recent error
 * produced on this thread, or `NULL` if there is no recorded error.
 *
 * The pointer is valid only until the next ctt call on this thread; copy
 * the string before making further calls if you need to keep it.
 */
 const char *ctt_last_error_message(void);

/**
 * Clear the thread-local error message slot.
 */
 void ctt_clear_last_error(void);

/**
 * Create an empty image of the given kind.
 */
 ctt_image *ctt_image_create(ctt_texture_kind kind);

/**
 * Destroy an image. `img` may be NULL.
 */
 void ctt_image_destroy(ctt_image *img);

/**
 * Append a new (empty) layer to the image.
 *
 * Writes the new layer's index into `*out_layer` if non-null. Returns
 * `CTT_STATUS_NULL_POINTER` if `img` is null.
 */
 ctt_status ctt_image_add_layer(ctt_image *img, size_t *out_layer);

/**
 * Push a mip level onto an existing layer. **Consumes** the surface — on
 * both success and failure the surface handle is destroyed; the caller
 * must not call `ctt_surface_destroy` on it.
 */
 ctt_status ctt_image_push_mip(ctt_image *img, size_t layer, ctt_surface *surface);

/**
 * Number of layers in the image. Returns `0` if `img` is null.
 */
 size_t ctt_image_layer_count(const ctt_image *img);

/**
 * Number of mip levels stored in `layer`. Returns `0` if `img` is null or
 * `layer` is out of range.
 */
 size_t ctt_image_mip_count(const ctt_image *img, size_t layer);

/**
 * Texture kind of the image. Returns `CTT_TEXTURE_KIND_TEXTURE2D` if `img`
 * is null.
 */
 ctt_texture_kind ctt_image_kind(const ctt_image *img);

/**
 * Allocate a freshly cloned `ctt_surface_t` for the surface at the given
 * `(layer, mip)` coordinates. The returned handle is independent of the
 * image and must be destroyed via `ctt_surface_destroy`.
 *
 * Returns NULL if `img` is null or the indices are out of range. Cloning
 * copies pixel/block data, which can be expensive for large surfaces; use
 * the field accessors below to read metadata or borrow the data buffer.
 */
 ctt_surface *ctt_image_clone_surface(const ctt_image *img, size_t layer, size_t mip);

/**
 * Pointer to the data buffer of one surface inside the image. Valid for as
 * long as the image lives and is not mutated. Returns `NULL` if `img` is
 * null or `(layer, mip)` is out of range.
 */
 const uint8_t *ctt_image_surface_data(const ctt_image *img, size_t layer, size_t mip);

/**
 * Length in bytes of one surface's data buffer. Returns `0` if `img` is
 * null or `(layer, mip)` is out of range.
 */
 size_t ctt_image_surface_data_len(const ctt_image *img, size_t layer, size_t mip);

/**
 * Width in pixels of the surface at `(layer, mip)`. Returns `0` if `img` is
 * null or `(layer, mip)` is out of range.
 */
 uint32_t ctt_image_surface_width(const ctt_image *img, size_t layer, size_t mip);

/**
 * Height in pixels of the surface at `(layer, mip)`. Returns `0` if `img`
 * is null or `(layer, mip)` is out of range.
 */
 uint32_t ctt_image_surface_height(const ctt_image *img, size_t layer, size_t mip);

/**
 * Depth (Z slice count) of the surface at `(layer, mip)`. `1` for 2D
 * surfaces. Returns `0` if `img` is null or `(layer, mip)` is out of range.
 */
 uint32_t ctt_image_surface_depth(const ctt_image *img, size_t layer, size_t mip);

/**
 * Row stride in bytes of the surface at `(layer, mip)`. Returns `0` if
 * `img` is null or `(layer, mip)` is out of range.
 */
 uint32_t ctt_image_surface_stride(const ctt_image *img, size_t layer, size_t mip);

/**
 * Z-slice stride in bytes of the surface at `(layer, mip)`. Meaningful only
 * when `depth > 1`. Returns `0` if `img` is null or `(layer, mip)` is out
 * of range.
 */
 uint32_t ctt_image_surface_slice_stride(const ctt_image *img, size_t layer, size_t mip);

/**
 * VkFormat of the surface at `(layer, mip)`. Returns `0`
 * (`VK_FORMAT_UNDEFINED`) if `img` is null or `(layer, mip)` is out of
 * range.
 */
 ctt_format ctt_image_surface_format(const ctt_image *img, size_t layer, size_t mip);

/**
 * Color space of the surface at `(layer, mip)`. Returns
 * `CTT_COLOR_SPACE_LINEAR` if `img` is null or `(layer, mip)` is out of
 * range.
 */
 ctt_color_space ctt_image_surface_color_space(const ctt_image *img, size_t layer, size_t mip);

/**
 * Alpha mode of the surface at `(layer, mip)`. Returns
 * `CTT_ALPHA_MODE_STRAIGHT` if `img` is null or `(layer, mip)` is out of
 * range.
 */
 ctt_alpha_mode ctt_image_surface_alpha(const ctt_image *img, size_t layer, size_t mip);

 ctt_input_overrides ctt_input_overrides_default(void);

/**
 * Detect whether `data` is a recognized container.
 *
 * Returns `true` and writes the format into `*out_format` if recognized,
 * `false` otherwise. `out_format` may be NULL.
 */
 bool ctt_detect_container(const uint8_t *data, size_t len, ctt_input_format *out_format);

/**
 * Decode a container, auto-detecting format from magic bytes.
 *
 * On success writes a freshly allocated `ctt_image_t` into `*out_image`.
 * `*out_recognized` (if non-null) is set to `true` when the data was a
 * recognized container; when it is `false`, `*out_image` is set to NULL
 * and the status code is `CTT_STATUS_OK` (not an error).
 *
 * `overrides` may be NULL to use defaults.
 */

ctt_status ctt_decode_container(const uint8_t *data,
                                size_t len,
                                const ctt_input_overrides *overrides,
                                ctt_image **out_image,
                                bool *out_recognized);

/**
 * Decode a container with the format chosen explicitly, bypassing magic
 * detection. Useful when the caller already knows which container they are
 * pointing at.
 *
 * `overrides` may be NULL to use defaults.
 */

ctt_status ctt_decode_container_as(const uint8_t *data,
                                   size_t len,
                                   ctt_input_format format,
                                   const ctt_input_overrides *overrides,
                                   ctt_image **out_image);

/**
 * Destroy a pipeline output. `out` may be NULL.
 */
 void ctt_pipeline_output_destroy(ctt_pipeline_output *out);

/**
 * Return the variant tag of the output.
 */
 ctt_pipeline_output_kind ctt_pipeline_output_get_kind(const ctt_pipeline_output *out);

/**
 * Pointer to the encoded container bytes. Valid until the output is
 * destroyed. Returns NULL when `out` is null or the tag is `Raw`.
 */
 const uint8_t *ctt_pipeline_output_encoded_data(const ctt_pipeline_output *out);

/**
 * Length in bytes of the encoded data, or `0` if the tag is `Raw`.
 */
 size_t ctt_pipeline_output_encoded_len(const ctt_pipeline_output *out);

/**
 * Take the `ctt_image_t` out of a `Raw` output, transferring ownership
 * to the caller. The output handle remains live for tag queries and must
 * still be destroyed via [`ctt_pipeline_output_destroy`], but a second
 * call to this function returns NULL.
 *
 * Returns NULL if `out` is null, the tag is not `Raw`, or the image has
 * already been taken.
 */
 ctt_image *ctt_pipeline_output_take_image(ctt_pipeline_output *out);

/**
 * Create a new surface, copying `data_len` bytes from `data` into Rust's
 * allocator.
 *
 * `format` must be a valid VkFormat value (non-zero). `slice_stride` is
 * only meaningful when `depth > 1`; pass `0` for 2D surfaces.
 *
 * On failure returns `NULL` and sets the thread-local error message.
 */

ctt_surface *ctt_surface_create(const uint8_t *data,
                                size_t data_len,
                                uint32_t width,
                                uint32_t height,
                                uint32_t depth,
                                uint32_t stride,
                                uint32_t slice_stride,
                                ctt_format format,
                                ctt_color_space color_space,
                                ctt_alpha_mode alpha);

/**
 * Destroy a surface. `s` may be NULL.
 */
 void ctt_surface_destroy(ctt_surface *s);

/**
 * Pointer to the surface's pixel/block bytes. Valid as long as the surface
 * exists and is not modified or consumed. Returns `NULL` if `s` is null.
 */
 const uint8_t *ctt_surface_data(const ctt_surface *s);

/**
 * Length in bytes of the surface's data buffer. Returns `0` if `s` is null.
 */
 size_t ctt_surface_data_len(const ctt_surface *s);

/**
 * Width in pixels of the surface. Returns `0` if `s` is null.
 */
 uint32_t ctt_surface_width(const ctt_surface *s);

/**
 * Height in pixels of the surface. Returns `0` if `s` is null.
 */
 uint32_t ctt_surface_height(const ctt_surface *s);

/**
 * Depth (Z slice count) of the surface. `1` for 2D surfaces. Returns `0`
 * if `s` is null.
 */
 uint32_t ctt_surface_depth(const ctt_surface *s);

/**
 * Row stride in bytes. Returns `0` if `s` is null.
 */
 uint32_t ctt_surface_stride(const ctt_surface *s);

/**
 * Z-slice stride in bytes. Meaningful only when `depth > 1`. Returns `0`
 * if `s` is null.
 */
 uint32_t ctt_surface_slice_stride(const ctt_surface *s);

/**
 * VkFormat of the surface. Returns `0` (`VK_FORMAT_UNDEFINED`) if `s` is
 * null.
 */
 ctt_format ctt_surface_format(const ctt_surface *s);

/**
 * Color space of the surface. Returns `CTT_COLOR_SPACE_LINEAR` if `s` is
 * null.
 */
 ctt_color_space ctt_surface_color_space(const ctt_surface *s);

/**
 * Alpha mode of the surface. Returns `CTT_ALPHA_MODE_STRAIGHT` if `s` is
 * null.
 */
 ctt_alpha_mode ctt_surface_alpha(const ctt_surface *s);

/**
 * Deep-copy a surface (data and metadata).
 *
 * On failure returns `NULL` and sets the thread-local error message.
 */
 ctt_surface *ctt_surface_clone(const ctt_surface *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CTT_H */
