[package]
name = "ctt-bc7enc-rdo"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors = ["The ctt developers", "Rich Geldreich <richgel99@gmail.com>"]
license = "(MIT OR Apache-2.0) AND Apache-2.0"
rust-version.workspace = true
readme = "../../README.md"
description = "Vendored bc7enc_rdo bindings with ISPC bc7e encoder"
keywords = ["texture", "compression", "bc7", "gpu"]
categories = ["graphics", "compression"]
build = "build.rs"

[features]
default = ["prebuilt"]
prebuilt = ["dep:ctt-bc7enc-rdo-prebuilt"]
build-from-source = []

[dependencies]
ctt-bc7enc-rdo-prebuilt = { workspace = true, optional = true }

[build-dependencies]
ispc-build-utils = { workspace = true }

[lints]
workspace = true
