#![allow(rustdoc::private_intra_doc_links)]
//! Safe Rust bindings to ARM's [astcenc](https://github.com/ARM-software/astc-encoder) library
//! for ASTC texture compression and decompression.
//!
//! # ISA dispatch
//!
//! The astcenc library uses compile-time SIMD ISA selection — the entire library is compiled
//! once per ISA variant. To get optimal performance on each CPU, this crate compiles multiple
//! variants and selects the best one at runtime:
//!
//! - **x86_64**: SSE2, SSE4.1, and AVX2 variants (selected via `std::is_x86_feature_detected!`)
//! - **aarch64**: NEON (the only variant, always available on AArch64)
//!
//! The build script (`build.rs`) compiles each variant into a separate static library with
//! preprocessor symbol renaming (`-Dastcenc_config_init=astcenc_sse2_config_init`, etc.) to
//! avoid link-time symbol conflicts. At runtime, a [`Dispatch`] table of function pointers is
//! initialized once via `OnceLock` and all public API calls go through it.
//!
//! # Bindings layout
//!
//! - [`bindings`] — **generated by bindgen** (`cargo xtask generate-bindings`). The raw FFI
//!   surface: C types, integer enums, `ASTCENC_*` constants. Use this when you need to read
//!   or write a `bindings::astcenc_config` field that the high-level wrappers
//!   don't expose (power-user `tune_*` knobs, custom progress callbacks, etc.).
//! - This crate's root — hand-written safe wrappers ([`Flags`], [`Profile`], [`Preset`],
//!   [`SwizzleChannel`], [`Swizzle`], [`Context`], [`config_init`]). Most callers should only
//!   need these.
//! - `src/lib.rs` (this file) also carries the ISA-prefixed `extern "C"` declarations in the
//!   private `ffi` module and the runtime [`Dispatch`] table.

pub mod bindings;

use std::ffi::CStr;
use std::ptr;
use std::sync::OnceLock;

// Internal-only glob: lets the wrapper code below name `astcenc_*` types and
// `ASTCENC_*` constants unqualified. Not re-exported — public callers reach
// these through the `bindings` module.
use bindings::*;

// ── Safe wrappers around bindgen integer constants ─────────────────────────────

bitflags::bitflags! {
    /// Compressor flags, passed to [`config_init`].
    ///
    /// Each bit corresponds to one of the `ASTCENC_FLG_*` constants from the
    /// underlying C header; the bit values are sourced from the generated
    /// bindings rather than duplicated here.
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Default)]
    pub struct Flags: u32 {
        /// Treat input as a 2-channel normal map and optimize for angular
        /// (rather than linear) error. Requires a 2-channel encoding swizzle
        /// (`rrrg` or `gggr`).
        const MAP_NORMAL = ASTCENC_FLG_MAP_NORMAL;
        /// Tune for the `decode_unorm8` decode mode rather than `decode_fp16`.
        ///
        /// ASTC blocks can be decoded by the GPU two ways: as fp16 (the
        /// historical default, exact) or as unorm8 (rounded to 8-bit). The
        /// two paths round differently in the last bit, so the encoder picks
        /// slightly different bit patterns to land on whichever the runtime
        /// will use. Mismatched flag + decode mode costs a small amount of
        /// quality; matched gains it back.
        ///
        /// Set this when the texture will be sampled as a unorm8 texel format
        /// at runtime (the common case for color textures on mobile and most
        /// modern desktop pipelines). Leave it off for HDR sampled as fp16.
        /// LDR sRGB always decodes via unorm8 regardless of this flag.
        const USE_DECODE_UNORM8 = ASTCENC_FLG_USE_DECODE_UNORM8;
        /// Weight RGB error by alpha so transparent regions trade RGB
        /// fidelity for better alpha precision.
        const USE_ALPHA_WEIGHT = ASTCENC_FLG_USE_ALPHA_WEIGHT;
        /// Optimize for perceptual error rather than PSNR. Only supported by
        /// some encoding modes (notably color and normal maps).
        const USE_PERCEPTUAL = ASTCENC_FLG_USE_PERCEPTUAL;
        /// Build a decompress-only context (rejects compression calls; uses
        /// less memory).
        const DECOMPRESS_ONLY = ASTCENC_FLG_DECOMPRESS_ONLY;
        /// Promise the context will only be asked to decompress images that
        /// it itself produced. Shrinks internal lookup tables and speeds up
        /// context creation; cannot reliably decompress arbitrary ASTC data.
        const SELF_DECOMPRESS_ONLY = ASTCENC_FLG_SELF_DECOMPRESS_ONLY;
        /// Treat input as HDR data preprocessed into LDR RGBM form.
        ///
        /// RGBM is a "fake HDR" encoding: HDR color is stored in an LDR
        /// 4-channel texture where RGB holds a normalized color and the M
        /// (alpha) channel holds a per-pixel shared multiplier. The shader
        /// reconstructs the HDR value as `rgb * m * rgbm_m_scale`. This lets
        /// you ship HDR-ish content through LDR-only formats and lightmaps
        /// at the cost of some banding in highlights and accuracy loss when
        /// `m` quantizes near zero.
        ///
        /// **The caller is responsible for the RGBM encoding** — this flag
        /// only tells the codec to use RGBM-aware heuristics and error
        /// metrics. Tune the multiplier with
        /// [`astcenc_config::rgbm_m_scale`](bindings::astcenc_config) and
        /// follow the upstream guidance to floor `m` (typically at `16/255`
        /// or `32/255`) before encoding so quantization can't round it to
        /// zero — that would produce black or NaN pixels.
        const MAP_RGBM = ASTCENC_FLG_MAP_RGBM;
    }
}

/// ASTC color profile (LDR linear, LDR sRGB, HDR-RGB+LDR-A, full HDR).
///
/// Picks the dynamic range and gamma assumptions the codec uses; must match
/// how the texture will be sampled at runtime.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Profile {
    /// 8-bit sRGB-gamma RGB with linear alpha.
    LdrSrgb,
    /// 8-bit linear LDR.
    Ldr,
    /// HDR RGB (fp16) with LDR alpha. Recommended for most HDR color data.
    HdrRgbLdrA,
    /// HDR across all four channels.
    Hdr,
}

impl Profile {
    /// Raw `astcenc_profile` value expected by the C API.
    pub fn as_raw(self) -> astcenc_profile {
        match self {
            Self::LdrSrgb => astcenc_profile_ASTCENC_PRF_LDR_SRGB,
            Self::Ldr => astcenc_profile_ASTCENC_PRF_LDR,
            Self::HdrRgbLdrA => astcenc_profile_ASTCENC_PRF_HDR_RGB_LDR_A,
            Self::Hdr => astcenc_profile_ASTCENC_PRF_HDR,
        }
    }
}

/// Quality preset for the compressor search.
///
/// The astcenc library accepts any float in `[0.0, 100.0]`; the named variants
/// map to the documented points (faster → lower quality). `Custom` exposes the
/// full continuum and is clamped to the valid range on use.
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Preset {
    /// 0.0 — fastest, lowest quality.
    Fastest,
    /// 10.0 — fast.
    Fast,
    /// 60.0 — medium.
    Medium,
    /// 98.0 — thorough.
    Thorough,
    /// 99.0 — very thorough.
    VeryThorough,
    /// 100.0 — exhaustive, highest quality.
    Exhaustive,
    /// Any value in `[0.0, 100.0]`. Performance is not linear across the range.
    Custom(f32),
}

impl Preset {
    /// Quality value clamped into the codec's supported `[0.0, 100.0]` range.
    pub fn as_float(self) -> f32 {
        let v = match self {
            Self::Fastest => ASTCENC_PRE_FASTEST,
            Self::Fast => ASTCENC_PRE_FAST,
            Self::Medium => ASTCENC_PRE_MEDIUM,
            Self::Thorough => ASTCENC_PRE_THOROUGH,
            Self::VeryThorough => ASTCENC_PRE_VERYTHOROUGH,
            Self::Exhaustive => ASTCENC_PRE_EXHAUSTIVE,
            Self::Custom(v) => v,
        };
        v.clamp(0.0, 100.0)
    }
}

/// One channel of a [`Swizzle`].
///
/// `R`/`G`/`B`/`A` pick a source component; `Zero` and `One` are constants;
/// `Z` reconstructs the third axis of a unit normal from the other two and
/// is only valid as part of a decode swizzle.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum SwizzleChannel {
    R,
    G,
    B,
    A,
    Zero,
    One,
    /// Reconstructed normal Z (`sqrt(1 - x² - y²)`). Decode only.
    Z,
}

impl SwizzleChannel {
    /// Raw `astcenc_swz` value expected by the C API.
    pub fn as_raw(self) -> astcenc_swz {
        match self {
            Self::R => astcenc_swz_ASTCENC_SWZ_R,
            Self::G => astcenc_swz_ASTCENC_SWZ_G,
            Self::B => astcenc_swz_ASTCENC_SWZ_B,
            Self::A => astcenc_swz_ASTCENC_SWZ_A,
            Self::Zero => astcenc_swz_ASTCENC_SWZ_0,
            Self::One => astcenc_swz_ASTCENC_SWZ_1,
            Self::Z => astcenc_swz_ASTCENC_SWZ_Z,
        }
    }
}

/// Four-component texel swizzle, applied before compression or after
/// decompression depending on which API takes it.
///
/// Use [`Swizzle::IDENTITY`] for `rgba` (no remap). The helpers cover the
/// patterns the upstream docs call out as worth coding to:
/// `rrr1` for single-channel data, `rrrg` / `gggr` for 2-channel and normals,
/// and `rgb1` for 3-channel.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct Swizzle {
    pub r: SwizzleChannel,
    pub g: SwizzleChannel,
    pub b: SwizzleChannel,
    pub a: SwizzleChannel,
}

impl Swizzle {
    /// `rgba` — pass each component through unchanged.
    pub const IDENTITY: Self = Self {
        r: SwizzleChannel::R,
        g: SwizzleChannel::G,
        b: SwizzleChannel::B,
        a: SwizzleChannel::A,
    };

    /// `rrr1` — replicate red into RGB and constant-1 alpha. Use for single-
    /// channel data (luminance, roughness, AO).
    pub const RRR1: Self = Self {
        r: SwizzleChannel::R,
        g: SwizzleChannel::R,
        b: SwizzleChannel::R,
        a: SwizzleChannel::One,
    };

    /// `rrrg` — replicate red into RGB and put green into alpha. Use for
    /// 2-channel data and the ASTC-default normal map layout.
    pub const RRRG: Self = Self {
        r: SwizzleChannel::R,
        g: SwizzleChannel::R,
        b: SwizzleChannel::R,
        a: SwizzleChannel::G,
    };

    /// `gggr` — replicate green into RGB and put red into alpha. The BC5n-
    /// compatible normal map layout.
    pub const GGGR: Self = Self {
        r: SwizzleChannel::G,
        g: SwizzleChannel::G,
        b: SwizzleChannel::G,
        a: SwizzleChannel::R,
    };

    /// `rgb1` — pass RGB through and force alpha to 1. Use for 3-channel data
    /// where alpha would otherwise waste encoding bits.
    pub const RGB1: Self = Self {
        r: SwizzleChannel::R,
        g: SwizzleChannel::G,
        b: SwizzleChannel::B,
        a: SwizzleChannel::One,
    };

    /// Convert to the raw struct expected by the C API.
    pub fn as_raw(self) -> astcenc_swizzle {
        astcenc_swizzle {
            r: self.r.as_raw(),
            g: self.g.as_raw(),
            b: self.b.as_raw(),
            a: self.a.as_raw(),
        }
    }
}

impl Default for Swizzle {
    fn default() -> Self {
        Self::IDENTITY
    }
}

// ── Error handling ─────────────────────────────────────────────────────────────

/// An error returned by the astcenc library.
#[derive(Debug, Clone)]
pub struct Error {
    #[allow(dead_code)]
    code: astcenc_error,
    message: String,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "astcenc error: {}", self.message)
    }
}

impl std::error::Error for Error {}

fn check(code: astcenc_error) -> Result<(), Error> {
    if code == astcenc_error_ASTCENC_SUCCESS {
        Ok(())
    } else {
        let msg = unsafe {
            let ptr = (dispatch().get_error_string)(code);
            if ptr.is_null() {
                "unknown error".to_string()
            } else {
                CStr::from_ptr(ptr).to_string_lossy().into_owned()
            }
        };
        Err(Error { code, message: msg })
    }
}

// ── Config ─────────────────────────────────────────────────────────────────────

/// Initialize an `astcenc_config` with codec defaults for the given parameters.
///
/// The returned config can be tuned before passing to [`Context::new`] —
/// in particular per-channel error weights (`cw_*_weight`), `rgbm_m_scale`,
/// and the `tune_*` power-user knobs.
pub fn config_init(
    profile: Profile,
    block_x: u32,
    block_y: u32,
    block_z: u32,
    preset: Preset,
    flags: Flags,
) -> Result<astcenc_config, Error> {
    let mut config = unsafe { std::mem::zeroed::<astcenc_config>() };
    let code = unsafe {
        (dispatch().config_init)(
            profile.as_raw(),
            block_x,
            block_y,
            block_z,
            preset.as_float(),
            flags.bits(),
            &mut config,
        )
    };
    check(code)?;
    Ok(config)
}

// ── Context ────────────────────────────────────────────────────────────────────

/// An opaque handle wrapping `astcenc_context`.
///
/// Manages the lifecycle of the context (freed on drop). All methods take
/// `&mut self` because the underlying C library mutates internal state during
/// compression and decompression and provides **no** internal synchronization.
///
/// # Threading limitations
///
/// This wrapper currently hardcodes `thread_count = 1` and always uses
/// `thread_index = 0`. The astcenc library supports a fork/join threading
/// model where multiple threads call into the same context with distinct
/// `thread_index` values. To support that in the future, one could:
///
/// - Accept a `thread_count` parameter in [`Context::new`].
/// - Expose `thread_index` on `compress` / `decompress`.
/// - Use an internal synchronization primitive (or `unsafe impl Sync`) to
///   allow concurrent access with the required per-phase barriers that
///   astcenc expects between compression stages.
pub struct Context {
    ptr: *mut astcenc_context,
}

// SAFETY: The raw pointer is not aliased — all methods require `&mut self`,
// so only one thread can access the context at a time.
unsafe impl Send for Context {}

impl Context {
    /// Allocate a new single-threaded context.
    pub fn new(config: &astcenc_config) -> Result<Self, Error> {
        let mut ctx: *mut astcenc_context = ptr::null_mut();
        let code = unsafe { (dispatch().context_alloc)(config, 1, &mut ctx, ptr::null()) };
        check(code)?;
        Ok(Self { ptr: ctx })
    }

    /// Compress an image into ASTC format.
    ///
    /// `swizzle` is applied to the input before compression.
    /// `output` must be large enough to hold the compressed data:
    /// `ceil(width / block_x) * ceil(height / block_y) * 16` bytes.
    pub fn compress(
        &mut self,
        image: &mut astcenc_image,
        swizzle: Swizzle,
        output: &mut [u8],
    ) -> Result<(), Error> {
        let raw = swizzle.as_raw();
        let code = unsafe {
            (dispatch().compress_image)(self.ptr, image, &raw, output.as_mut_ptr(), output.len(), 0)
        };
        check(code)
    }

    /// Reset the compressor state so another image can be compressed using the
    /// same context.
    pub fn compress_reset(&mut self) -> Result<(), Error> {
        let code = unsafe { (dispatch().compress_reset)(self.ptr) };
        check(code)
    }

    /// Decompress ASTC data into an image. `swizzle` is applied after the raw
    /// decode (useful for reconstructing normal Z via [`SwizzleChannel::Z`]).
    pub fn decompress(
        &mut self,
        data: &[u8],
        image_out: &mut astcenc_image,
        swizzle: Swizzle,
    ) -> Result<(), Error> {
        let raw = swizzle.as_raw();
        let code = unsafe {
            (dispatch().decompress_image)(self.ptr, data.as_ptr(), data.len(), image_out, &raw, 0)
        };
        check(code)
    }

    /// Reset the decompressor state between images.
    pub fn decompress_reset(&mut self) -> Result<(), Error> {
        let code = unsafe { (dispatch().decompress_reset)(self.ptr) };
        check(code)
    }
}

impl Drop for Context {
    fn drop(&mut self) {
        if !self.ptr.is_null() {
            unsafe { (dispatch().context_free)(self.ptr) };
        }
    }
}

// ── Runtime ISA dispatch ───────────────────────────────────────────────────────
//
// Each ISA variant (SSE2, SSE4.1, AVX2, NEON) is compiled as a separate static
// library with all public API symbols renamed via preprocessor macros
// (e.g. `astcenc_config_init` → `astcenc_sse2_config_init`). See `build.rs`.
//
// The `ffi` module below declares `extern "C"` bindings for every ISA-prefixed
// symbol. At startup, `init_dispatch()` probes CPU features and fills a
// `Dispatch` function-pointer table with the best available variant. All safe
// wrappers above call through `dispatch()`.

/// Function pointer table for the selected ISA variant.
struct Dispatch {
    config_init: unsafe extern "C" fn(
        astcenc_profile,
        u32,
        u32,
        u32,
        f32,
        u32,
        *mut astcenc_config,
    ) -> astcenc_error,
    context_alloc: unsafe extern "C" fn(
        *const astcenc_config,
        u32,
        *mut *mut astcenc_context,
        *const astcenc_context,
    ) -> astcenc_error,
    context_free: unsafe extern "C" fn(*mut astcenc_context),
    compress_image: unsafe extern "C" fn(
        *mut astcenc_context,
        *mut astcenc_image,
        *const astcenc_swizzle,
        *mut u8,
        usize,
        u32,
    ) -> astcenc_error,
    compress_reset: unsafe extern "C" fn(*mut astcenc_context) -> astcenc_error,
    #[allow(dead_code)]
    compress_cancel: unsafe extern "C" fn(*mut astcenc_context) -> astcenc_error,
    decompress_image: unsafe extern "C" fn(
        *mut astcenc_context,
        *const u8,
        usize,
        *mut astcenc_image,
        *const astcenc_swizzle,
        u32,
    ) -> astcenc_error,
    decompress_reset: unsafe extern "C" fn(*mut astcenc_context) -> astcenc_error,
    get_error_string: unsafe extern "C" fn(astcenc_error) -> *const std::ffi::c_char,
}

// SAFETY: Dispatch only contains function pointers, which are Send+Sync.
unsafe impl Send for Dispatch {}
unsafe impl Sync for Dispatch {}

fn dispatch() -> &'static Dispatch {
    static DISPATCH: OnceLock<Dispatch> = OnceLock::new();
    DISPATCH.get_or_init(init_dispatch)
}

// ── ISA-specific extern "C" declarations ───────────────────────────────────────
//
// These correspond to the renamed symbols emitted by `build.rs`. For example,
// on x86_64 the SSE2 build compiles with `-Dastcenc_config_init=astcenc_sse2_config_init`,
// so the linker sees `astcenc_sse2_config_init` as an extern "C" symbol.

#[cfg(target_arch = "x86_64")]
mod ffi {
    use super::bindings::*;

    macro_rules! declare_isa {
        ($isa:ident) => {
            paste::paste! {
                unsafe extern "C" {
                    pub fn [<astcenc_ $isa _config_init>](
                        profile: astcenc_profile,
                        block_x: u32,
                        block_y: u32,
                        block_z: u32,
                        quality: f32,
                        flags: u32,
                        config: *mut astcenc_config,
                    ) -> astcenc_error;

                    pub fn [<astcenc_ $isa _context_alloc>](
                        config: *const astcenc_config,
                        thread_count: u32,
                        context: *mut *mut astcenc_context,
                        parent_context: *const astcenc_context,
                    ) -> astcenc_error;

                    pub fn [<astcenc_ $isa _context_free>](context: *mut astcenc_context);

                    pub fn [<astcenc_ $isa _compress_image>](
                        context: *mut astcenc_context,
                        image: *mut astcenc_image,
                        swizzle: *const astcenc_swizzle,
                        data_out: *mut u8,
                        data_len: usize,
                        thread_index: u32,
                    ) -> astcenc_error;

                    pub fn [<astcenc_ $isa _compress_reset>](
                        context: *mut astcenc_context,
                    ) -> astcenc_error;

                    pub fn [<astcenc_ $isa _compress_cancel>](
                        context: *mut astcenc_context,
                    ) -> astcenc_error;

                    pub fn [<astcenc_ $isa _decompress_image>](
                        context: *mut astcenc_context,
                        data: *const u8,
                        data_len: usize,
                        image_out: *mut astcenc_image,
                        swizzle: *const astcenc_swizzle,
                        thread_index: u32,
                    ) -> astcenc_error;

                    pub fn [<astcenc_ $isa _decompress_reset>](
                        context: *mut astcenc_context,
                    ) -> astcenc_error;

                    pub fn [<astcenc_ $isa _get_error_string>](
                        status: astcenc_error,
                    ) -> *const std::ffi::c_char;
                }
            }
        };
    }

    declare_isa!(sse2);
    declare_isa!(sse41);
    declare_isa!(avx2);
}

#[cfg(target_arch = "aarch64")]
mod ffi {
    use super::bindings::*;

    unsafe extern "C" {
        pub fn astcenc_neon_config_init(
            profile: astcenc_profile,
            block_x: u32,
            block_y: u32,
            block_z: u32,
            quality: f32,
            flags: u32,
            config: *mut astcenc_config,
        ) -> astcenc_error;

        pub fn astcenc_neon_context_alloc(
            config: *const astcenc_config,
            thread_count: u32,
            context: *mut *mut astcenc_context,
            parent_context: *const astcenc_context,
        ) -> astcenc_error;

        pub fn astcenc_neon_context_free(context: *mut astcenc_context);

        pub fn astcenc_neon_compress_image(
            context: *mut astcenc_context,
            image: *mut astcenc_image,
            swizzle: *const astcenc_swizzle,
            data_out: *mut u8,
            data_len: usize,
            thread_index: u32,
        ) -> astcenc_error;

        pub fn astcenc_neon_compress_reset(context: *mut astcenc_context) -> astcenc_error;

        pub fn astcenc_neon_compress_cancel(context: *mut astcenc_context) -> astcenc_error;

        pub fn astcenc_neon_decompress_image(
            context: *mut astcenc_context,
            data: *const u8,
            data_len: usize,
            image_out: *mut astcenc_image,
            swizzle: *const astcenc_swizzle,
            thread_index: u32,
        ) -> astcenc_error;

        pub fn astcenc_neon_decompress_reset(context: *mut astcenc_context) -> astcenc_error;

        pub fn astcenc_neon_get_error_string(status: astcenc_error) -> *const std::ffi::c_char;
    }
}

// ── Dispatch initialization ────────────────────────────────────────────────────

#[cfg(target_arch = "x86_64")]
fn init_dispatch() -> Dispatch {
    macro_rules! make_dispatch {
        ($isa:ident) => {
            paste::paste! {
                Dispatch {
                    config_init: ffi::[<astcenc_ $isa _config_init>],
                    context_alloc: ffi::[<astcenc_ $isa _context_alloc>],
                    context_free: ffi::[<astcenc_ $isa _context_free>],
                    compress_image: ffi::[<astcenc_ $isa _compress_image>],
                    compress_reset: ffi::[<astcenc_ $isa _compress_reset>],
                    compress_cancel: ffi::[<astcenc_ $isa _compress_cancel>],
                    decompress_image: ffi::[<astcenc_ $isa _decompress_image>],
                    decompress_reset: ffi::[<astcenc_ $isa _decompress_reset>],
                    get_error_string: ffi::[<astcenc_ $isa _get_error_string>],
                }
            }
        };
    }

    if is_x86_feature_detected!("avx2") {
        make_dispatch!(avx2)
    } else if is_x86_feature_detected!("sse4.1") {
        make_dispatch!(sse41)
    } else {
        make_dispatch!(sse2)
    }
}

#[cfg(target_arch = "aarch64")]
fn init_dispatch() -> Dispatch {
    Dispatch {
        config_init: ffi::astcenc_neon_config_init,
        context_alloc: ffi::astcenc_neon_context_alloc,
        context_free: ffi::astcenc_neon_context_free,
        compress_image: ffi::astcenc_neon_compress_image,
        compress_reset: ffi::astcenc_neon_compress_reset,
        compress_cancel: ffi::astcenc_neon_compress_cancel,
        decompress_image: ffi::astcenc_neon_decompress_image,
        decompress_reset: ffi::astcenc_neon_decompress_reset,
        get_error_string: ffi::astcenc_neon_get_error_string,
    }
}
