#![allow(rustdoc::private_intra_doc_links)]
//! Safe Rust bindings to ARM's [astcenc](https://github.com/ARM-software/astc-encoder) library
//! for ASTC texture compression and decompression.
//!
//! # ISA dispatch
//!
//! The astcenc library uses compile-time SIMD ISA selection — the entire library is compiled
//! once per ISA variant. To get optimal performance on each CPU, this crate compiles multiple
//! variants and selects the best one at runtime:
//!
//! - **x86_64**: SSE2, SSE4.1, and AVX2 variants (selected via `std::is_x86_feature_detected!`)
//! - **aarch64**: NEON (the only variant, always available on AArch64)
//!
//! The build script (`build.rs`) compiles each variant into a separate static library with
//! preprocessor symbol renaming (`-Dastcenc_config_init=astcenc_sse2_config_init`, etc.) to
//! avoid link-time symbol conflicts. At runtime, a [`Dispatch`] table of function pointers is
//! initialized once via `OnceLock` and all public API calls go through it.
//!
//! # Bindings layout
//!
//! - `src/bindings/mod.rs` — **generated by bindgen** (`cargo xtask generate-bindings`).
//!   Contains only types, constants, and enum values. No function declarations — those live
//!   here in `lib.rs` with ISA-prefixed names (see the `ffi` module below).
//! - `src/lib.rs` (this file) — hand-written ISA-prefixed `extern "C"` declarations in the
//!   `ffi` module, the runtime dispatch table, and safe Rust wrappers.

mod bindings;

use std::ffi::CStr;
use std::ptr;
use std::sync::OnceLock;

// Re-export all generated types and constants.
pub use bindings::*;

// ── Error handling ─────────────────────────────────────────────────────────────

/// An error returned by the astcenc library.
#[derive(Debug, Clone)]
pub struct Error {
    #[allow(dead_code)]
    code: astcenc_error,
    message: String,
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "astcenc error: {}", self.message)
    }
}

impl std::error::Error for Error {}

fn check(code: astcenc_error) -> Result<(), Error> {
    if code == astcenc_error_ASTCENC_SUCCESS {
        Ok(())
    } else {
        let msg = unsafe {
            let ptr = (dispatch().get_error_string)(code);
            if ptr.is_null() {
                "unknown error".to_string()
            } else {
                CStr::from_ptr(ptr).to_string_lossy().into_owned()
            }
        };
        Err(Error { code, message: msg })
    }
}

// ── Config ─────────────────────────────────────────────────────────────────────

/// Initialize an `astcenc_config` with default settings for the given parameters.
///
/// The returned config can be further tuned before passing to [`Context::new`].
pub fn config_init(
    profile: astcenc_profile,
    block_x: u32,
    block_y: u32,
    block_z: u32,
    quality: f32,
    flags: u32,
) -> Result<astcenc_config, Error> {
    let mut config = unsafe { std::mem::zeroed::<astcenc_config>() };
    let code = unsafe {
        (dispatch().config_init)(
            profile,
            block_x,
            block_y,
            block_z,
            quality,
            flags,
            &mut config,
        )
    };
    check(code)?;
    Ok(config)
}

// ── Context ────────────────────────────────────────────────────────────────────

/// An opaque handle wrapping `astcenc_context`.
///
/// Manages the lifecycle of the context (freed on drop).
pub struct Context {
    ptr: *mut astcenc_context,
}

// SAFETY: The astcenc context is internally synchronized for the threading model
// we use (single thread_index=0). It's safe to send across threads.
unsafe impl Send for Context {}
unsafe impl Sync for Context {}

impl Context {
    /// Allocate a new context. `thread_count` is the number of threads that will
    /// call compress/decompress concurrently.
    pub fn new(config: &astcenc_config, thread_count: u32) -> Result<Self, Error> {
        let mut ctx: *mut astcenc_context = ptr::null_mut();
        let code =
            unsafe { (dispatch().context_alloc)(config, thread_count, &mut ctx, ptr::null()) };
        check(code)?;
        Ok(Self { ptr: ctx })
    }

    /// Compress an image into ASTC format.
    ///
    /// `output` must be large enough to hold the compressed data:
    /// `ceil(width / block_x) * ceil(height / block_y) * 16` bytes.
    pub fn compress(
        &self,
        image: &mut astcenc_image,
        swizzle: &astcenc_swizzle,
        output: &mut [u8],
        thread_index: u32,
    ) -> Result<(), Error> {
        let code = unsafe {
            (dispatch().compress_image)(
                self.ptr,
                image,
                swizzle,
                output.as_mut_ptr(),
                output.len(),
                thread_index,
            )
        };
        check(code)
    }

    /// Reset the compressor state so another image can be compressed using the
    /// same context. Required between images when using multi-threaded compression.
    pub fn compress_reset(&self) -> Result<(), Error> {
        let code = unsafe { (dispatch().compress_reset)(self.ptr) };
        check(code)
    }

    /// Decompress ASTC data into an image.
    pub fn decompress(
        &self,
        data: &[u8],
        image_out: &mut astcenc_image,
        swizzle: &astcenc_swizzle,
        thread_index: u32,
    ) -> Result<(), Error> {
        let code = unsafe {
            (dispatch().decompress_image)(
                self.ptr,
                data.as_ptr(),
                data.len(),
                image_out,
                swizzle,
                thread_index,
            )
        };
        check(code)
    }

    /// Reset the decompressor state between images.
    pub fn decompress_reset(&self) -> Result<(), Error> {
        let code = unsafe { (dispatch().decompress_reset)(self.ptr) };
        check(code)
    }
}

impl Drop for Context {
    fn drop(&mut self) {
        if !self.ptr.is_null() {
            unsafe { (dispatch().context_free)(self.ptr) };
        }
    }
}

// ── Runtime ISA dispatch ───────────────────────────────────────────────────────
//
// Each ISA variant (SSE2, SSE4.1, AVX2, NEON) is compiled as a separate static
// library with all public API symbols renamed via preprocessor macros
// (e.g. `astcenc_config_init` → `astcenc_sse2_config_init`). See `build.rs`.
//
// The `ffi` module below declares `extern "C"` bindings for every ISA-prefixed
// symbol. At startup, `init_dispatch()` probes CPU features and fills a
// `Dispatch` function-pointer table with the best available variant. All safe
// wrappers above call through `dispatch()`.

/// Function pointer table for the selected ISA variant.
struct Dispatch {
    config_init: unsafe extern "C" fn(
        astcenc_profile,
        u32,
        u32,
        u32,
        f32,
        u32,
        *mut astcenc_config,
    ) -> astcenc_error,
    context_alloc: unsafe extern "C" fn(
        *const astcenc_config,
        u32,
        *mut *mut astcenc_context,
        *const astcenc_context,
    ) -> astcenc_error,
    context_free: unsafe extern "C" fn(*mut astcenc_context),
    compress_image: unsafe extern "C" fn(
        *mut astcenc_context,
        *mut astcenc_image,
        *const astcenc_swizzle,
        *mut u8,
        usize,
        u32,
    ) -> astcenc_error,
    compress_reset: unsafe extern "C" fn(*mut astcenc_context) -> astcenc_error,
    #[allow(dead_code)]
    compress_cancel: unsafe extern "C" fn(*mut astcenc_context) -> astcenc_error,
    decompress_image: unsafe extern "C" fn(
        *mut astcenc_context,
        *const u8,
        usize,
        *mut astcenc_image,
        *const astcenc_swizzle,
        u32,
    ) -> astcenc_error,
    decompress_reset: unsafe extern "C" fn(*mut astcenc_context) -> astcenc_error,
    get_error_string: unsafe extern "C" fn(astcenc_error) -> *const std::ffi::c_char,
}

// SAFETY: Dispatch only contains function pointers, which are Send+Sync.
unsafe impl Send for Dispatch {}
unsafe impl Sync for Dispatch {}

fn dispatch() -> &'static Dispatch {
    static DISPATCH: OnceLock<Dispatch> = OnceLock::new();
    DISPATCH.get_or_init(init_dispatch)
}

// ── ISA-specific extern "C" declarations ───────────────────────────────────────
//
// These correspond to the renamed symbols emitted by `build.rs`. For example,
// on x86_64 the SSE2 build compiles with `-Dastcenc_config_init=astcenc_sse2_config_init`,
// so the linker sees `astcenc_sse2_config_init` as an extern "C" symbol.

#[cfg(target_arch = "x86_64")]
mod ffi {
    use super::bindings::*;

    macro_rules! declare_isa {
        ($isa:ident) => {
            paste::paste! {
                unsafe extern "C" {
                    pub fn [<astcenc_ $isa _config_init>](
                        profile: astcenc_profile,
                        block_x: u32,
                        block_y: u32,
                        block_z: u32,
                        quality: f32,
                        flags: u32,
                        config: *mut astcenc_config,
                    ) -> astcenc_error;

                    pub fn [<astcenc_ $isa _context_alloc>](
                        config: *const astcenc_config,
                        thread_count: u32,
                        context: *mut *mut astcenc_context,
                        parent_context: *const astcenc_context,
                    ) -> astcenc_error;

                    pub fn [<astcenc_ $isa _context_free>](context: *mut astcenc_context);

                    pub fn [<astcenc_ $isa _compress_image>](
                        context: *mut astcenc_context,
                        image: *mut astcenc_image,
                        swizzle: *const astcenc_swizzle,
                        data_out: *mut u8,
                        data_len: usize,
                        thread_index: u32,
                    ) -> astcenc_error;

                    pub fn [<astcenc_ $isa _compress_reset>](
                        context: *mut astcenc_context,
                    ) -> astcenc_error;

                    pub fn [<astcenc_ $isa _compress_cancel>](
                        context: *mut astcenc_context,
                    ) -> astcenc_error;

                    pub fn [<astcenc_ $isa _decompress_image>](
                        context: *mut astcenc_context,
                        data: *const u8,
                        data_len: usize,
                        image_out: *mut astcenc_image,
                        swizzle: *const astcenc_swizzle,
                        thread_index: u32,
                    ) -> astcenc_error;

                    pub fn [<astcenc_ $isa _decompress_reset>](
                        context: *mut astcenc_context,
                    ) -> astcenc_error;

                    pub fn [<astcenc_ $isa _get_error_string>](
                        status: astcenc_error,
                    ) -> *const std::ffi::c_char;
                }
            }
        };
    }

    declare_isa!(sse2);
    declare_isa!(sse41);
    declare_isa!(avx2);
}

#[cfg(target_arch = "aarch64")]
mod ffi {
    use super::bindings::*;

    unsafe extern "C" {
        pub fn astcenc_neon_config_init(
            profile: astcenc_profile,
            block_x: u32,
            block_y: u32,
            block_z: u32,
            quality: f32,
            flags: u32,
            config: *mut astcenc_config,
        ) -> astcenc_error;

        pub fn astcenc_neon_context_alloc(
            config: *const astcenc_config,
            thread_count: u32,
            context: *mut *mut astcenc_context,
            parent_context: *const astcenc_context,
        ) -> astcenc_error;

        pub fn astcenc_neon_context_free(context: *mut astcenc_context);

        pub fn astcenc_neon_compress_image(
            context: *mut astcenc_context,
            image: *mut astcenc_image,
            swizzle: *const astcenc_swizzle,
            data_out: *mut u8,
            data_len: usize,
            thread_index: u32,
        ) -> astcenc_error;

        pub fn astcenc_neon_compress_reset(context: *mut astcenc_context) -> astcenc_error;

        pub fn astcenc_neon_compress_cancel(context: *mut astcenc_context) -> astcenc_error;

        pub fn astcenc_neon_decompress_image(
            context: *mut astcenc_context,
            data: *const u8,
            data_len: usize,
            image_out: *mut astcenc_image,
            swizzle: *const astcenc_swizzle,
            thread_index: u32,
        ) -> astcenc_error;

        pub fn astcenc_neon_decompress_reset(context: *mut astcenc_context) -> astcenc_error;

        pub fn astcenc_neon_get_error_string(status: astcenc_error) -> *const std::ffi::c_char;
    }
}

// ── Dispatch initialization ────────────────────────────────────────────────────

#[cfg(target_arch = "x86_64")]
fn init_dispatch() -> Dispatch {
    macro_rules! make_dispatch {
        ($isa:ident) => {
            paste::paste! {
                Dispatch {
                    config_init: ffi::[<astcenc_ $isa _config_init>],
                    context_alloc: ffi::[<astcenc_ $isa _context_alloc>],
                    context_free: ffi::[<astcenc_ $isa _context_free>],
                    compress_image: ffi::[<astcenc_ $isa _compress_image>],
                    compress_reset: ffi::[<astcenc_ $isa _compress_reset>],
                    compress_cancel: ffi::[<astcenc_ $isa _compress_cancel>],
                    decompress_image: ffi::[<astcenc_ $isa _decompress_image>],
                    decompress_reset: ffi::[<astcenc_ $isa _decompress_reset>],
                    get_error_string: ffi::[<astcenc_ $isa _get_error_string>],
                }
            }
        };
    }

    if is_x86_feature_detected!("avx2") {
        make_dispatch!(avx2)
    } else if is_x86_feature_detected!("sse4.1") {
        make_dispatch!(sse41)
    } else {
        make_dispatch!(sse2)
    }
}

#[cfg(target_arch = "aarch64")]
fn init_dispatch() -> Dispatch {
    Dispatch {
        config_init: ffi::astcenc_neon_config_init,
        context_alloc: ffi::astcenc_neon_context_alloc,
        context_free: ffi::astcenc_neon_context_free,
        compress_image: ffi::astcenc_neon_compress_image,
        compress_reset: ffi::astcenc_neon_compress_reset,
        compress_cancel: ffi::astcenc_neon_compress_cancel,
        decompress_image: ffi::astcenc_neon_decompress_image,
        decompress_reset: ffi::astcenc_neon_decompress_reset,
        get_error_string: ffi::astcenc_neon_get_error_string,
    }
}
