[package]
name = "ctt-cli"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../README.md"
description = "Command-line interface for the ctt texture compression library"
keywords = ["texture", "compression", "gpu", "cli"]
categories = ["command-line-utilities", "graphics"]
default-run = "ctt"
autotests = false

[features]
default = ["ispc-prebuilt"]
ispc-prebuilt = ["ctt/ispc-prebuilt"]
ispc-build-from-source = ["ctt/ispc-build-from-source"]

[lib]
name = "ctt_cli"
path = "src/lib.rs"

[[bin]]
name = "ctt"
path = "src/main.rs"
doc = false

[[test]]
name = "root"
path = "tests/root.rs"

[dependencies]
ctt = { workspace = true, features = [
  "encoder-amd",
  "encoder-astcenc",
  "encoder-bc7enc",
  "encoder-etcpak",
  "encoder-intel",
] }
clap = { workspace = true, features = ["wrap_help"] }
image = { workspace = true, features = ["default"] }
bytemuck = { workspace = true }
fern = { workspace = true }
profiling = { workspace = true }
log = { workspace = true }

[dev-dependencies]
ktx2 = { workspace = true }
ddsfile = { workspace = true }
tempfile = { workspace = true }

[lints]
workspace = true
