[package]
name = "ispc-build-utils"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Utilities for compiling ISPC source files in build scripts"

[features]
default = []
verify-hash = ["dep:sha2"]

[dependencies]
find-msvc-tools = "0.1.9"
sha2 = { version = "0.10", optional = true }

[lints]
workspace = true
