/* automatically generated by rust-bindgen 0.72.1 */

// Generated by bindgen — regenerate with `cargo xtask generate-bindings`.
#![allow(non_camel_case_types, non_upper_case_globals, dead_code)]

pub const cPackBC7FlagUse2SubsetsRGB: _bindgen_ty_1 = 1;
pub const cPackBC7FlagUse2SubsetsRGBA: _bindgen_ty_1 = 2;
pub const cPackBC7FlagUse3SubsetsRGB: _bindgen_ty_1 = 4;
pub const cPackBC7FlagUseDualPlaneRGB: _bindgen_ty_1 = 8;
pub const cPackBC7FlagUseDualPlaneRGBA: _bindgen_ty_1 = 16;
pub const cPackBC7FlagPBitOpt: _bindgen_ty_1 = 32;
pub const cPackBC7FlagPBitOptMode6: _bindgen_ty_1 = 64;
pub const cPackBC7FlagUseTrivialMode6: _bindgen_ty_1 = 128;
pub const cPackBC7FlagPartiallyAnalyticalRGB: _bindgen_ty_1 = 256;
pub const cPackBC7FlagPartiallyAnalyticalRGBA: _bindgen_ty_1 = 512;
pub const cPackBC7FlagNonAnalyticalRGB: _bindgen_ty_1 = 1024;
pub const cPackBC7FlagNonAnalyticalRGBA: _bindgen_ty_1 = 2048;
pub const cPackBC7FlagASTCCompatible: _bindgen_ty_1 = 4096;
pub const cPackBC7FlagDisableRGBDualPlane: _bindgen_ty_1 = 8192;
pub const cPackBC7FlagDefaultFastest: _bindgen_ty_1 = 128;
pub const cPackBC7FlagDefaultFaster: _bindgen_ty_1 = 176;
pub const cPackBC7FlagDefaultFast: _bindgen_ty_1 = 179;
pub const cPackBC7FlagDefault: _bindgen_ty_1 = 255;
pub const cPackBC7FlagDefaultPartiallyAnalytical: _bindgen_ty_1 = 1023;
pub const cPackBC7FlagDefaultNonAnalytical: _bindgen_ty_1 = 3967;
pub type _bindgen_ty_1 = ::std::os::raw::c_uint;
unsafe extern "C" {
    pub fn ctt_bc7f_init();
}
unsafe extern "C" {
    pub fn ctt_bc7f_compress_blocks(output: *mut u8, pixels: *const u8, count: usize, flags: u32);
}
