use std::path::Path;

use anyhow::{Result, ensure};

use crate::util::workspace_root;

/// Display a path relative to the workspace root.
fn rel(workspace_root: &Path, path: &Path) -> String {
    path.strip_prefix(workspace_root)
        .unwrap_or(path)
        .display()
        .to_string()
}

pub fn generate_bindings() -> Result<()> {
    let workspace_root = workspace_root();

    // Use a shared temp dir for all ISPC compilations.
    let tmp = std::env::temp_dir().join("ctt-bindgen");
    std::fs::create_dir_all(&tmp)?;
    let host_target =
        ispc_build_utils::CompileTarget::from_triple(&current_host_triple(), tmp.clone());

    generate_astcenc_bindings(&workspace_root)?;
    generate_compressonator_bindings(&workspace_root)?;

    // kernel.rs — compile kernel.ispc to get the ISPC-generated header
    {
        let ispc_dir = workspace_root.join("crates/ctt-intel-texture-compressor/ispc");
        let out = workspace_root.join("crates/ctt-intel-texture-compressor/src/bindings/kernel.rs");

        println!("[3/4] Generating kernel.rs");

        println!("      Compiling kernel.ispc with ISPC...");
        let mut config = ispc_build_utils::Config::new();
        config
            .file(ispc_dir.join("kernel.ispc"))
            .opt_level(0)
            .woff();
        config.compile_to("kernel", &host_target);

        let header = tmp.join("ispc_kernel/kernel_ispc.h");
        ensure!(
            header.exists(),
            "ISPC did not generate kernel_ispc.h at {}",
            header.display()
        );

        // Parse in C mode so the `namespace ispc {}` guard is inactive.
        // Force-include stdbool.h since the ISPC header's __STDC_VERSION__
        // guard may not fire under bindgen's clang.
        println!("      Running bindgen on kernel_ispc.h...");
        let bindings = bindgen::Builder::default()
            .header(header.to_str().unwrap())
            .clang_arg("-std=c11")
            .clang_arg("-Wno-pragma-once-outside-header")
            .clang_arg("-include")
            .clang_arg("stdbool.h")
            .allowlist_function("CompressBlocksBC1_ispc")
            .allowlist_function("CompressBlocksBC3_ispc")
            .allowlist_function("CompressBlocksBC4_ispc")
            .allowlist_function("CompressBlocksBC5_ispc")
            .allowlist_function("CompressBlocksBC6H_ispc")
            .allowlist_function("CompressBlocksBC7_ispc")
            .allowlist_function("CompressBlocksETC1_ispc")
            .allowlist_type("rgba_surface")
            .allowlist_type("bc7_enc_settings")
            .allowlist_type("bc6h_enc_settings")
            .allowlist_type("etc_enc_settings")
            .layout_tests(false)
            .generate_comments(false)
            .raw_line("// Generated by bindgen — regenerate with `cargo xtask generate-bindings`.")
            .raw_line("//")
            .raw_line("// Source: ispc/kernel.ispc")
            .raw_line("#![allow(non_camel_case_types, non_snake_case, dead_code)]")
            .generate()
            .expect("failed to generate kernel bindings");

        bindings
            .write_to_file(&out)
            .expect("failed to write kernel.rs");
        normalize_line_endings(&out);
        println!("      Wrote {}", rel(&workspace_root, &out));
    }

    // bc7e.rs — compile bc7e.ispc to get the generated header, then bindgen
    {
        let ispc_dir = workspace_root.join("crates/ctt-bc7enc-rdo/ispc");
        let out = workspace_root.join("crates/ctt-bc7enc-rdo/src/bindings.rs");

        println!("[4/4] Generating bc7e.rs");

        println!("      Compiling bc7e.ispc with ISPC...");
        let mut config = ispc_build_utils::Config::new();
        config.file(ispc_dir.join("bc7e.ispc")).opt_level(0).woff();
        config.compile_to("bc7e", &host_target);

        let header = tmp.join("ispc_bc7e/bc7e_ispc.h");
        ensure!(
            header.exists(),
            "ISPC did not generate bc7e_ispc.h at {}",
            header.display()
        );

        // ISPC names anonymous inner structs $anon0, $anon1, etc.
        // Rename them to descriptive names before running bindgen.
        rename_ispc_anon_structs(
            &header,
            &[
                ("$anon0", "bc7e_compress_block_params_opaque"),
                ("$anon1", "bc7e_compress_block_params_alpha"),
            ],
        );

        println!("      Running bindgen on bc7e_ispc.h...");
        let bindings = bindgen::Builder::default()
            .header(header.to_str().unwrap())
            .clang_arg("-std=c11")
            .clang_arg("-Wno-pragma-once-outside-header")
            .clang_arg("-include")
            .clang_arg("stdbool.h")
            .allowlist_function("bc7e_compress_block_init")
            .allowlist_function("bc7e_compress_blocks")
            .allowlist_function("bc7e_compress_block_params_init.*")
            .allowlist_type("bc7e_compress_block_params.*")
            .layout_tests(false)
            .generate_comments(false)
            .raw_line("// Generated by bindgen — regenerate with `cargo xtask generate-bindings`.")
            .raw_line("//")
            .raw_line("// Source: ispc/bc7e.ispc")
            .raw_line("#![allow(non_camel_case_types, non_snake_case, dead_code)]")
            .generate()
            .expect("failed to generate bc7e bindings");

        bindings
            .write_to_file(&out)
            .expect("failed to write bc7e.rs");
        normalize_line_endings(&out);
        println!("      Wrote {}", rel(&workspace_root, &out));
    }

    // Clean up temp dir.
    let _ = std::fs::remove_dir_all(&tmp);

    Ok(())
}

fn generate_astcenc_bindings(workspace_root: &Path) -> Result<()> {
    let header = workspace_root.join("crates/ctt-astcenc/cpp/astcenc.h");
    let out = workspace_root.join("crates/ctt-astcenc/src/bindings.rs");

    println!("[1/4] Generating bindings.rs (astcenc)");

    ensure!(
        header.exists(),
        "astcenc.h not found at {} — run vendor.sh first",
        header.display()
    );

    println!("      Running bindgen on astcenc.h...");
    let bindings = bindgen::Builder::default()
        .header(header.to_str().unwrap())
        .clang_arg("-x")
        .clang_arg("c++")
        .clang_arg("-std=c++14")
        // Satisfy ISA preprocessor guards without pulling in SIMD types.
        .clang_arg("-DASTCENC_SSE=0")
        .clang_arg("-DASTCENC_AVX=0")
        .clang_arg("-DASTCENC_NEON=0")
        .clang_arg("-DASTCENC_SVE=0")
        .clang_arg("-DASTCENC_POPCNT=0")
        .clang_arg("-DASTCENC_F16C=0")
        // Types only — function declarations are hand-written in lib.rs
        // with ISA-prefixed names for runtime dispatch.
        .allowlist_type("astcenc_error")
        .allowlist_type("astcenc_profile")
        .allowlist_type("astcenc_swz")
        .allowlist_type("astcenc_type")
        .allowlist_type("astcenc_config")
        .allowlist_type("astcenc_context")
        .allowlist_type("astcenc_image")
        .allowlist_type("astcenc_swizzle")
        .allowlist_type("astcenc_block_info")
        // Constants
        .allowlist_var("ASTCENC_PRE_.*")
        .allowlist_var("ASTCENC_FLG_.*")
        .allowlist_var("ASTCENC_ALL_FLAGS")
        .layout_tests(false)
        .generate_comments(false)
        .raw_line(
            "//! Raw FFI bindings to the astcenc C API.
//!
//! Most callers should reach for the high-level wrappers in the crate root
//! instead. This module is exposed for power-user cases where
//! you need to set a field on [`astcenc_config`] that the
//! wrappers don't surface — `tune_*` heuristics, progress callbacks, custom
//! per-channel error weights, RGBM scale, and so on.

",
        )
        .raw_line("// Generated by bindgen — regenerate with `cargo xtask generate-bindings`.")
        .raw_line("//")
        .raw_line("// Source: cpp/astcenc.h")
        .raw_line(
            "#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals, dead_code)]",
        )
        .generate()
        .expect("failed to generate astcenc bindings");

    bindings
        .write_to_file(&out)
        .expect("failed to write astcenc.rs");
    normalize_line_endings(&out);
    println!("      Wrote {}", rel(workspace_root, &out));

    Ok(())
}

fn generate_compressonator_bindings(workspace_root: &Path) -> Result<()> {
    let header = workspace_root.join("crates/ctt-compressonator/cpp/source/cmp_core.h");
    let out = workspace_root.join("crates/ctt-compressonator/src/bindings.rs");

    println!("[2/4] Generating bindings.rs (compressonator)");

    ensure!(
        header.exists(),
        "cmp_core.h not found at {} — run vendor.sh first",
        header.display()
    );

    println!("      Running bindgen on cmp_core.h...");
    // The header has `extern "C"` guards so C++ parsing still produces
    // C-linkage symbols. We parse as C++ because common_def.h (included
    // for the CGU_ERROR_CODES enum) transitively pulls in <cmath>.
    let cmp_root = workspace_root.join("crates/ctt-compressonator/cpp");
    let bindings = bindgen::Builder::default()
        .header(header.to_str().unwrap())
        .clang_arg("-x")
        .clang_arg("c++")
        .clang_arg("-std=c++14")
        .clang_arg("-DCMP_DEFAULTNULL=")
        .clang_arg("-DCMP_CDECL=")
        // Include paths so common_def.h can find its transitive includes.
        .clang_arg(format!("-I{}", cmp_root.join("source").display()))
        .clang_arg(format!("-I{}", cmp_root.join("shaders").display()))
        .clang_arg(format!("-I{}", cmp_root.join("cmp_math").display()))
        // Pull in common_def.h for the CGU_ERROR_CODES enum.
        .clang_arg("-include")
        .clang_arg(cmp_root.join("shaders/common_def.h").to_str().unwrap())
        .allowlist_function("Create.*")
        .allowlist_function("Destroy.*")
        .allowlist_function("Set.*")
        .allowlist_function("CompressBlock.*")
        .allowlist_function("DecompressBlock.*")
        .allowlist_function("EnableSSE4")
        .allowlist_function("EnableAVX2")
        .allowlist_function("EnableAVX512")
        .allowlist_function("DisableSIMD")
        .allowlist_function("GetEnabledSIMDExtension")
        .allowlist_type("CGU_ERROR_CODES")
        .allowlist_var("CGU_CORE_.*")
        .layout_tests(false)
        .generate_comments(false)
        .raw_line("// Generated by bindgen — regenerate with `cargo xtask generate-bindings`.")
        .raw_line("//")
        .raw_line("// Source: cpp/source/cmp_core.h")
        .raw_line(
            "#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals, dead_code)]",
        )
        .generate()
        .expect("failed to generate compressonator bindings");

    bindings
        .write_to_file(&out)
        .expect("failed to write compressonator bindings.rs");
    normalize_line_endings(&out);
    println!("      Wrote {}", rel(workspace_root, &out));

    Ok(())
}

/// Rename ISPC-generated anonymous struct names (e.g. `$anon0`) to
/// descriptive names in the header file, in-place.
fn rename_ispc_anon_structs(header: &Path, renames: &[(&str, &str)]) {
    let mut content = std::fs::read_to_string(header).expect("failed to read ISPC header");
    for (from, to) in renames {
        content = content.replace(from, to);
    }
    std::fs::write(header, content).expect("failed to write renamed ISPC header");
}

/// Returns the host target triple string.
fn current_host_triple() -> String {
    let arch = std::env::consts::ARCH;
    let os = std::env::consts::OS;

    match (arch, os) {
        ("x86_64", "linux") => "x86_64-unknown-linux-gnu".to_string(),
        ("aarch64", "linux") => "aarch64-unknown-linux-gnu".to_string(),
        ("x86_64", "windows") => "x86_64-pc-windows-msvc".to_string(),
        ("aarch64", "windows") => "aarch64-pc-windows-msvc".to_string(),
        ("x86_64", "macos") => "x86_64-apple-darwin".to_string(),
        ("aarch64", "macos") => "aarch64-apple-darwin".to_string(),
        _ => panic!("unsupported host platform: {arch}-{os}"),
    }
}

/// Normalize a file to LF line endings.
fn normalize_line_endings(path: &Path) {
    let content = std::fs::read_to_string(path).expect("failed to read file for normalization");
    if content.contains('\r') {
        let normalized = content.replace("\r\n", "\n");
        std::fs::write(path, normalized).expect("failed to write normalized file");
    }
}
