[package]
name = "ctt-astcenc"
version.workspace = true
edition.workspace = true
repository.workspace = true
authors.workspace = true
license = "(MIT OR Apache-2.0 OR Zlib) AND Apache-2.0"
rust-version.workspace = true
readme = "../../README.md"
description = "Vendored astcenc bindings for ASTC texture compression"
keywords = ["texture", "compression", "astc", "gpu"]
categories = ["graphics", "compression"]
build = "build.rs"
links = "astcenc"

[dependencies]
bitflags = { workspace = true }
paste = { workspace = true }

[build-dependencies]
cc = { workspace = true, features = ["parallel"] }

[lints]
workspace = true
