[package]
name = "ctt"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
readme = "../../README.md"
description = "Compress images to GPU texture formats"
keywords = ["texture", "compression", "gpu", "bc7", "dds"]
categories = ["graphics", "compression"]

[features]
default = [
  "encoder-intel",
  "encoder-bc7enc",
  "encoder-etcpak",
  "encoder-astcenc",
  "encoder-amd",
  "ispc-prebuilt",
]
encoder-intel = ["dep:ctt-intel-texture-compressor"]
encoder-bc7enc = ["dep:ctt-bc7enc-rdo"]
encoder-etcpak = ["dep:ctt-etcpak"]
encoder-astcenc = ["dep:ctt-astcenc"]
encoder-amd = ["dep:ctt-compressonator"]
ispc-prebuilt = [
  "ctt-intel-texture-compressor?/prebuilt",
  "ctt-bc7enc-rdo?/prebuilt",
]
ispc-build-from-source = [
  "ctt-intel-texture-compressor?/build-from-source",
  "ctt-bc7enc-rdo?/build-from-source",
]

[dependencies]
bytemuck = { workspace = true, features = [
  "extern_crate_alloc",
  "min_const_generics",
] }
ctt-astcenc = { workspace = true, optional = true }
ctt-bc7enc-rdo = { workspace = true, optional = true }
ctt-compressonator = { workspace = true, optional = true }
ctt-etcpak = { workspace = true, optional = true }
ctt-intel-texture-compressor = { workspace = true, optional = true }
ddsfile = { workspace = true }
fast_image_resize = { workspace = true }
flate2 = { workspace = true }
half = { workspace = true }
ktx2 = { workspace = true }
log = { workspace = true }
miniz_oxide = { workspace = true }
profiling = { workspace = true }
thiserror = { workspace = true }
zstd = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "srgb"
harness = false

[[bench]]
name = "f16"
harness = false

[[bench]]
name = "packed"
harness = false

[lints]
workspace = true
