[package]
name = "ctt"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
ctt-intel-texture-compressor = { workspace = true }
thiserror = { workspace = true }
ddsfile = { workspace = true }
ktx2 = { workspace = true }

[lints]
workspace = true
